const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '../../..');
const source = 'V4/propositions/rilka-01/04b-vol-au-musee.png';
const common = `Use case: identity-preserve. Make a precise HAIRSTYLE-ONLY EDIT of the supplied Rilka museum-theft illustration. The supplied image is the EDIT TARGET, not merely inspiration.
LOCK EVERYTHING except the hair growing on top and behind her head: identical cheetah face and muzzle, amber eyes, alert upward sideways gaze, expression, ears, spotted fur, body proportions, long legs, athletic stance, hand positions, clothes, upper-arm wound, electric whip, blue relic, open glass cabinet, museum exhibits, architecture, lighting, palette, composition and crop. Do not beautify or humanize her face, alter makeup, enlarge eyes or breasts, change outfit, add jewelry or equipment, change her pose or make her look at the viewer. She remains the same mature adult female humanoid cheetah thief caught in the act of stealing, not a fashion portrait.
Replace ONLY the existing short asymmetric black hair with the hairstyle below. Hair must grow naturally between her small round cheetah ears and integrate around their bases, not cover them or create human ears. Leave both eyes, black facial tear markings and the action-oriented expression clearly visible. Hair is a tasteful humanlike hairstyle on a feline humanoid head, never a lion mane, wig, helmet or fur hood. Keep the exact hand-painted Kalistar medium of the input: broken brush planes, textured pigment, selectively defined strands, warm museum rim light. No photographic salon hair, no glossy CGI, no anime styling. The new hair can naturally occupy a little adjacent background or collar area, but otherwise preserve the original painting with maximum fidelity.
Return ONE complete full-bleed illustration at the original portrait aspect ratio, preferably the same 1122 x 1402 dimensions. Do not crop to a headshot, add borders, text, numbers, labels or multiple panels. This is one of six separate hairstyle studies; output only the specified hairstyle. Hair differences should be clearly readable at card size, not six almost-identical fringes.
HAIRSTYLE: `;
const items = [
  { n: 1, title: 'Pixie cuivre', file: '01-pixie-cuivre.png', hair: 'A genuinely short textured copper-auburn pixie cut, closely cropped at the nape with little feathered choppy pieces on top and a small side-swept fringe well above the eyes. Warm muted copper, darker roots, no huge quiff. Compact, athletic, spirited, feminine; visibly much shorter than the original hair.' },
  { n: 2, title: 'Carre asymetrique', file: '02-carre-asymetrique.png', hair: 'A sharp asymmetrical ink-black bob. One side tucked neatly behind the cheetah ear, the other angled section ending near the jaw, a clear sculpted diagonal silhouette, side part, both eyes unobscured. Subtle blue-black reflected light, matte hand-painted strands rather than glossy salon finish. Chic, poised, slightly cyberpunk, but the same alert thief in action.' },
  { n: 3, title: 'Queue haute', file: '03-queue-haute.png', hair: 'A practical high ponytail in deep dark chestnut brown. Hair swept backward between the cheetah ears, gathered at the crown with a plain dark tie; a lean ponytail reaches just behind the shoulder, with a little natural swing from her head turn. Two very fine loose strands near the temple, no bangs hiding the eyes. Clearly a tied ponytail, not an enormous mane. Athletic and elegant.' },
  { n: 4, title: 'Tresses plaquees', file: '04-tresses-plaquees.png', hair: 'Several neat close-to-scalp dark brown braids following the crown from front to back between the cheetah ears, gathered into a short slim braided tail at the nape. Show the directional braided pattern clearly but tastefully, without beads, jewelry or newly invented ornaments. Face and ears fully clear, compact functional silhouette with a few softer hairline wisps. Confident, precise, agile.' },
  { n: 5, title: 'Undercut platine', file: '05-undercut-platine.png', hair: 'A distinct modest cyberpunk undercut: closely clipped charcoal hair at the sides around the ear bases and a short swept-back pale ash-platinum top, with dark roots. A little asymmetric broken texture, no towering mohawk and no sharp anime spikes. Keep the pale hair naturally shaded by the museum light, not glowing white. Daring, lean, slightly rebellious; preserve the original adult feline face.' },
  { n: 6, title: 'Ondulations brunes', file: '06-ondulations-brunes.png', hair: 'Soft medium-length dark chocolate-brown waves ending just above the shoulders, loosely swept back from the face with an off-centre part. A few naturally escaping wave tips, restrained volume, both small round ears and both eyes still clearly visible. A relaxed, feminine organic silhouette distinct from the bob, braids and ponytail. Painted locks, no glamorous blowout or huge mane; the exact same tense museum-theft action remains.' }
];
for (const item of items) {
  item.promptFile = 'prompt-' + String(item.n).padStart(2, '0') + '.txt';
  item.prompt = common + item.hair;
  fs.writeFileSync(path.join(__dirname, item.promptFile), item.prompt);
}
const sha256 = crypto.createHash('sha256').update(fs.readFileSync(path.join(root, source))).digest('hex');
fs.writeFileSync(path.join(__dirname, 'specs.json'), JSON.stringify({ source, sourceSha256: sha256, items }, null, 2));
console.log(JSON.stringify({ count: items.length, source, sha256 }));
