const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '../../..');
const hash = p => crypto.createHash('sha256').update(fs.readFileSync(path.resolve(root, p))).digest('hex');
const references = ['V3/assets/illustrations/01_ELECTRO_MOMO.png', 'V3/assets/illustrations/34_NECRO_VALAZAR.png'];
const common = `Use case: illustration-story. Produce ONE standalone full-bleed portrait illustration, approximately 4:5 aspect ratio, for the original fantasy world KALISTAR. No card border, text, UI, panel, labels, watermark or collage.
REFERENCE ROLES: Image 1, Momo, and image 2, Valazar, are STYLE REFERENCES ONLY, not subjects to copy. Closely follow their traditional-looking narrative fantasy painting: visibly shaped brushstrokes, broken painterly edges, layered opaque pigment, rich but restrained color, weathered metals and textiles, expressive character, believable motivated lighting. Match this family of art, NOT a photograph, live action, glossy 3D game render, anime, comic superhero or flat toon. Do not copy their hats, robes, skeleton or robot anatomy.
SUBJECT: Rilka, an adult female Felineus cheetah-human hybrid thief in Chroma. Tall, very long elegant legs, slim athletic sprinter musculature and fashion-model proportions, strong supple stance, not exaggerated sexual anatomy. True expressive CHEETAH head with a short fine muzzle, small rounded ears, golden spotted fur, distinctive black tear-lines below amber eyes, feminine intelligent features and a mischievous self-assured expression. NOT a human face with cat ears, NOT a leopard or lynx head. Upright humanoid torso, exactly two human-proportioned arms and two very long human-proportioned legs, anatomically clear knees and hands. Sparse cheetah details on exposed extremities. No quadruped body or extra limbs. No large tail competing with the whip silhouette.
COSTUME: practical lightweight urban thief clothes, fitted matte technical trousers, short asymmetric jacket or fitted vest, fabric and worn leather panels, flexible flat-soled runner boots, small tool belt and a few salvaged copper conductive parts. Tasteful slight cyberpunk influence within Kalistar's tactile fantasy world, not glossy latex, underwear, bulky power armor, oversized shoulder pads or high heels. Clothing follows her athletic silhouette without sexualized framing.
WEAPON AND POWER: precisely ONE electric WHIP, held by a clearly visible hand, a single slender articulated conductive cable continuously traceable from its handle to its tip. Readable as a material whip with restrained golden electric sparks, never just a luminous ribbon or energy sword. Electricity also subtly flickers around one foot or ankle to convey bursts of speed. No full-body lightning explosion; face, torso and both long legs stay unobscured.
WORLD: Chroma is an inhabited fantasy-industrial city of layered workshops, roof walkways, salvaged brass and copper machinery, weathered metal, cables and repaired architecture. Use real depth and convincing construction. Only a few quiet cyan industrial lights; not a generic neon megacity, nightclub, cyberpunk franchise or blank studio backdrop.
COMPOSITION: single main character, full body including both feet and head visible, occupying about 78-85 percent of image height with some breathing room. Keep face, hands and important action away from outermost 12 percent side edges for future card rails. A clear flowing silhouette with unusually long legs readable. Environment enriches her story without overtaking her. Natural spatially correct lighting; detailed painted face and cloth, readable even as a small card. Avoid motion blur, lens bokeh, photorealistic fur, mechanical noise all over the image, giant neon signs or fake writing.
SPECIFIC PROPOSAL BELOW overrides only the pose, costume accents and setting, not these invariants. Do not make a sheet of alternatives. Render ONE polished narrative painting.`;
const items = [
  { n: 1, title: 'Un eclair d avance', file: '01-depart-sur-les-toits.png', scene: `Late afternoon rooftop launch. Rilka is taking the first powerful sprinting step along an elevated weathered copper catwalk, full body in an open three-quarter view, one long leg grounded and the other stretched back, chest and smiling face turning slightly toward the viewer. Her free hand keeps a small stolen energy module close to her belt. The whip is drawn behind her in a single broad open curve; a few sparks show where it brushes metal. Short graphite jacket with faded petrol-teal lining, fitted black technical trousers, copper ankle fasteners. Sun-warmed ivory clouds and peach light frame her spotted face; busy layered Chroma workshops descend far below, painted with the same emotional spaciousness as Momo's scrapyard. Mood: free, quick, playful, just one beat before she disappears. No pursuers or other characters.` },
  { n: 2, title: 'Sous la pluie de Chroma', file: '02-infiltration-sous-la-pluie.png', scene: `A quiet theft in a rain-damp service alley at blue hour. Rilka is upright, leaning lightly around the edge of a maintenance doorway, one long leg extended forward onto a step and the other straight behind, not crouched into a small ball. Her full lean silhouette remains visible. She looks back over her shoulder with a conspiratorial half smile, ears relaxed. One hand holds the electric whip, its cable in an easy long S close to the ground; the other has just removed a small component from an open wall cabinet. Sleeveless graphite utility vest over an opaque fitted shirt, tailored charcoal trousers with narrow faded turquoise side panels, fingerless work gloves, copper wrist fittings. Sparse cyan workshop lamps reflect on rain-darkened stone and worn metal; warm light spills from a nearby shutter gap and catches the face. Painterly rain, tangible matte fabrics, intimate clever-thief atmosphere; detailed but not neon-drenched, no other figures.` },
  { n: 3, title: 'Entre deux battements', file: '03-saut-des-passerelles.png', scene: `A poised dynamic leap across a modest gap between two workshop roof walkways in Chroma, viewed three-quarter at roughly her torso height, not from underneath. Rilka's full body is suspended in one readable sprinter's stride: forward knee lifted, rear leg extended, exactly two legs, no acrobatics, no dramatic foreshortening. Her face is focused and delighted, a small grin rather than an aggressive snarl. One hand holds the whip trailing in a clear cable arc; the free arm naturally balances the jump. Cropped weathered indigo jacket, pale grey technical shirt, fitted dark runner trousers, small brass buckles, flexible boots. Only a brief gold spark remains at her launch point and along the cable. Late afternoon cloud-filtered sun, pale green-blue sky, ochre brick, roof cables and old metal vents, lower city visible through the gap. The scene is visibly PAINTED like Momo, not a cinematic action screenshot. She is close enough for her face, long legs and clothing to read inside a portrait card.` },
  { n: 4, title: 'Le sourire du larcin', file: '04-sortie-du-coffre.png', scene: `Inside a tall narrow vault-workshop in Chroma, Rilka has just emerged through a partly opened heavy old copper security door. Full body standing in confident asymmetrical contrapposto, one very long leg crossing slightly ahead of the other, both feet visible and firmly grounded. Her distinctive cheetah head is turned toward us with a witty warm triumphant smile. She holds a small stolen glowing component in her free hand at waist height, while the whip hangs from its actual handle in her other hand, making one graceful open loop down beside her legs without hiding them. Sleek high-collared cropped graphite jacket with a small copper shoulder insert, dark plum fabric at the waist, fitted charcoal trousers and flat runner boots, no cape or gown. Amber mechanism light behind her outlines the silhouette; cool cyan ambient light from the corridor reveals her face and matte textiles. Patinated safe gears, workshop drawers and old wiring subtly establish the burglary. Intimate, elegant, recognizably fantasy, playful rather than sinister. No other characters and no readable bank logos.` },
  { n: 5, title: 'La ville sous ses pas', file: '05-equilibre-sur-chroma.png', scene: `A serene daring moment high above Chroma in the clear early morning. Rilka walks along a narrow horizontal maintenance beam, full body almost frontal three-quarter, spine upright, shoulders relaxed, one long leg straight supporting her and the other taking an elegant careful step forward. Both long legs and both feet are entirely visible. Her gaze turns toward us with a gentle cheeky smile, confident enough to pause and enjoy the view after a theft. One hand lightly grips the whip handle with its single long cable dropping in a loose curve alongside the beam; the other arm extends a little for balance. Short asymmetrical off-white weathered canvas jacket over a graphite fitted top, slim dark trousers, turquoise sash detail and little copper anklets, flexible flat boots. Tiny controlled golden sparks at her boot sole and on the whip contrast with soft daylight. Behind her are the sunlit stacked workshops, distant cranes, rooftop gardens in salvaged containers and hanging power lines of Chroma, painted in airy turquoise, pale apricot and copper. The city is lived in and beautiful without becoming a glossy futuristic skyline. Mood: freedom, affection for her city, a thief who makes danger look effortless. No giant tail and no extra figures.` }
];
for (const item of items) {
  item.promptFile = 'prompt-' + String(item.n).padStart(2, '0') + '.txt';
  item.prompt = common + '\n\nPROPOSAL ' + item.n + ': ' + item.scene;
  if (item.n > 1) item.prompt += '\nPAINTERLY PRIORITY: Paint the cheetah face itself in confident broken brush planes and simplified fur masses, with the expressive warm character of Momo. Do not switch to photographic animal fur or live-action creature makeup. Cloth, anatomy and city must share the same visibly hand-painted medium, not just a painted background behind a realistic head.';
  fs.writeFileSync(path.join(__dirname, item.promptFile), item.prompt);
}
fs.writeFileSync(path.join(__dirname, 'specs.json'), JSON.stringify({ references, items }, null, 2));
const protectedPaths = [...references, 'V4/template-stable/KALISTAR_V4_TEMPLATE_03C_ELECTRO_MOMO_BAL.psd', 'V3/donnees/cartes.json'];
for (const name of ['MOMO_V4_11_POSITIONS', 'TAULIO_V4_02_POSITIONS', 'JELLY_JOE_V4_03_ENCRE', 'MOMO_BAL_V4_01_TEMPLATE_ELECTRO']) protectedPaths.push('V4/templates/' + name + '.psd', 'V4/cartes/' + name + '.png');
const protectionPath = path.join(__dirname, 'protected.json');
if (!fs.existsSync(protectionPath)) fs.writeFileSync(protectionPath, JSON.stringify(Object.fromEntries(protectedPaths.map(p => [p, hash(p)])), null, 2));
console.log(JSON.stringify({ count: items.length, references, folder: __dirname }));
