'use strict';
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const assert = require('node:assert/strict');
const {createRequire} = require('node:module');
const {DIST, inside} = require('./build.cjs');
const runtime = process.env.KALISTAR_NODE_MODULES || path.join(process.env.USERPROFILE, '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const {chromium} = createRequire(path.join(runtime, '_pages_test.cjs'))('playwright');
const output = path.join(__dirname, 'verification');
const mime = {'.html':'text/html; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2'};
async function main() {
  const server = http.createServer((req,res) => {
    try {
      const url = new URL(req.url, 'http://localhost');
      if (!url.pathname.startsWith('/Kalistar/')) throw Error('Outside site');
      const rel = decodeURIComponent(url.pathname.slice('/Kalistar/'.length));
      const file = inside(DIST, rel.endsWith('/') || !rel ? rel + 'index.html' : rel);
      res.setHeader('Content-Type', mime[path.extname(file)] || 'application/octet-stream');
      res.setHeader('Cache-Control', 'no-store');
      res.end(fs.readFileSync(file));
    } catch {res.writeHead(404);res.end();}
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const local = 'http://127.0.0.1:' + server.address().port + '/Kalistar/';
  const base = process.env.KALISTAR_PAGES_URL || local;
  let browser;
  try {
    browser = await chromium.launch({channel: 'chrome', headless: true});
    fs.mkdirSync(output, {recursive:true});
    const context = await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
    const page = await context.newPage(), errors = [], failures = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('response', r => {if(r.status() >= 400) failures.push(r.status() + ' ' + r.url());});
    await page.goto(base);
    await page.waitForFunction(() => window.KALISTAR_READY);
    const {appManifest, manifestUrl} = await page.evaluate(async () => {
      const manifestUrl = new URL('manifest.webmanifest', location.href);
      return {appManifest: await (await fetch(manifestUrl)).json(), manifestUrl: manifestUrl.href};
    });
    assert.equal(appManifest.display, 'standalone');
    assert.equal(new URL(appManifest.start_url, manifestUrl).pathname, new URL('./', manifestUrl).pathname);
    assert.equal(await page.locator('[data-view=atelier]').count(), 0);
    assert.equal(await page.evaluate(() => KalistarSite.online), true);
    const count = await page.evaluate(() => KALISTAR_DATA.cards.length);
    assert.equal(await page.evaluate(() => KALISTAR_DB.registry.owned('user-paris').length), count);
    await page.waitForFunction(() => [...document.images].filter(i=>i.getClientRects().length).every(i=>i.complete&&i.naturalWidth>0&&!i.src.includes('#v4-')));
    await page.screenshot({path:path.join(output,'collection-desktop.png')});
    await page.locator('.cb-card').first().click();
    await page.locator('.cb-reader').waitFor();
    const href = await page.locator('.cb-visual a[download]').getAttribute('href');
    assert.ok(href.includes('/Kalistar/media/'));
    assert.equal((await page.request.get(href)).status(),200);
    await page.locator('[data-binder-action=back]').click();
    await page.locator('[data-view=decks]').first().click();
    await page.locator('#deck-builder-root').waitFor();
    await page.locator('#deck-builder-root .kdb-play').click();
    await page.locator('#new-game-form').waitFor();
    assert.equal(await page.locator('#new-game-dialog').evaluate(el=>el.classList.contains('pre-match-dialog')),true);
    assert.equal(await page.locator('#player-match-deck option').count()>=1,true);
    assert.equal(await page.locator('#match-player-preview .match-deck-topline>b').innerText().then(value=>value.includes('10')),true);
    assert.equal(await page.locator('#match-player-preview .match-lineup-card').count(),5);
    await page.locator('#game-mode').selectOption('local');
    assert.equal(await page.locator('#match-enemy-title').innerText(),'JOUEUR 2');
    assert.equal(await page.locator('#match-enemy-name').innerText(),'Joueur 2');
    const arenas=page.locator('.match-arena-choice input');
    assert.ok(await arenas.count()>=2);
    const secondArena=arenas.nth(1),secondArenaName=await secondArena.evaluate(el=>el.closest('label').innerText.trim());
    await secondArena.check({force:true});
    assert.equal(await page.locator('#match-arena-summary h3').innerText(),secondArenaName);
    await page.screenshot({path:path.join(output,'pre-match-desktop.png')});
    for(let i=0;i<20;i++)await page.locator('[data-action=match-arena-scroll][data-direction="1"]').click();
    const arenaRail=await page.locator('.match-arena-options').evaluate(el=>({left:el.scrollLeft,client:el.clientWidth,scroll:el.scrollWidth}));
    assert.ok(arenaRail.left>0&&arenaRail.left+arenaRail.client>=arenaRail.scroll-2,'Arena rail did not reach its end: '+JSON.stringify(arenaRail));
    const lastArena=arenas.nth(await arenas.count()-1),lastArenaName=await lastArena.evaluate(el=>el.closest('label').innerText.trim());
    await lastArena.check({force:true});
    assert.equal(await page.locator('#match-arena-summary h3').innerText(),lastArenaName);
    await page.setViewportSize({width:390,height:844});
    await page.waitForTimeout(250);
    const preMatchWidth=await page.locator('#new-game-dialog .pre-match-form').evaluate(el=>({scroll:el.scrollWidth,client:el.clientWidth}));
    assert.ok(preMatchWidth.scroll<=preMatchWidth.client+1,'Pre-match lobby overflows on phone: '+JSON.stringify(preMatchWidth));
    await page.screenshot({path:path.join(output,'pre-match-phone.png')});
    await page.locator('#new-game-dialog [data-action=close]').first().click();
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('[data-view=arena]').first().click();
    await page.waitForFunction(() => document.fullscreenElement === document.documentElement);
    await page.waitForFunction(() => document.body.classList.contains('arena-view'));
    assert.equal(await page.locator('.masthead').evaluate(el => getComputedStyle(el).display), 'none');
    assert.equal(await page.locator('.arena-toolbar .tools [data-action=new-game]').isVisible(), false);
    await page.locator('[data-action=arena-menu]').click();
    await page.locator('#mobile-dialog [data-action=save-game]').waitFor();
    await page.locator('#mobile-dialog [data-action=close]').click();
    await page.screenshot({path:path.join(output,'arena-immersive.png')});
    await page.locator('[data-action=exit-arena]').click();
    await page.locator('.cb-spread').waitFor();
    await page.waitForFunction(() => !document.fullscreenElement);
    await page.locator('[data-view=arena]').first().click();
    await page.waitForFunction(() => document.fullscreenElement === document.documentElement);
    await page.locator('[data-action=auto-formation]').first().click();
    await page.locator('[data-action=start]').first().click();
    const before = await page.evaluate(() => JSON.parse(localStorage.getItem('kalistar.v4.game')).matchId);
    await page.reload();
    await page.waitForFunction(() => window.KALISTAR_READY);
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('kalistar.v4.game')).matchId), before);
    await page.waitForFunction(() => [...document.images].filter(i=>i.getClientRects().length).every(i=>i.complete&&i.naturalWidth>0&&!i.src.includes('#v4-')));
    await page.screenshot({path:path.join(output,'arena-desktop.png')});
    await page.locator('.arena-toolbar [data-action=combat-reference][data-reference=elements]').click();
    await page.locator('#combat-reference-dialog[open]').waitFor();
    assert.equal(await page.locator('#combat-reference-dialog .element-matchup').count(),11);
    const waterFire=page.locator('.element-matchup[data-attacker=HYDRO][data-defender=PYRO]');
    assert.match(await waterFire.innerText(),/EAU[\s\S]*FEU[\s\S]*AVANTAGE ATK/);
    assert.ok(await waterFire.locator('img').evaluateAll(images=>images.every(img=>img.complete&&img.naturalWidth>0)));
    await page.screenshot({path:path.join(output,'combat-reference-crystals-desktop.png')});
    await page.locator('#combat-reference-dialog [data-action=close]').click();
    await page.locator('.arena-toolbar [data-action=combat-reference][data-reference=weapons]').click();
    assert.equal(await page.locator('#weapon-reference-grid .weapon-matchup').count(),20);
    await page.locator('#weapon-reference-attack').selectOption('Hache');
    assert.equal(await page.locator('.weapon-matchup[data-defender="Arc"] .weapon-modifier').innerText(),'-50');
    assert.equal(await page.locator('.weapon-matchup[data-defender="Dague"] .weapon-modifier').innerText(),'+50');
    await page.screenshot({path:path.join(output,'combat-reference-weapons-desktop.png')});
    await page.locator('#combat-reference-dialog [data-action=close]').click();
    await page.setViewportSize({width:412,height:1007});
    await page.waitForTimeout(500);
    assert.ok(await page.locator('.slot-card img').count() >= 10);
    assert.equal(await page.locator('.arena-reference-dock [data-action=combat-reference]').count(),2);
    assert.equal(await page.locator('.arena-reference-dock [data-reference=elements]').isVisible(),true);
    await page.locator('.arena-reference-dock [data-reference=elements]').click();
    const crystalDialog=await page.locator('#combat-reference-dialog').evaluate(el=>({width:el.getBoundingClientRect().width,client:el.clientWidth,scroll:el.scrollWidth,bodyClient:el.querySelector('.combat-reference').clientWidth,bodyScroll:el.querySelector('.combat-reference').scrollWidth}));
    assert.ok(crystalDialog.width<=412&&crystalDialog.scroll<=crystalDialog.client+1&&crystalDialog.bodyScroll<=crystalDialog.bodyClient+1,'Crystal reference overflows on phone: '+JSON.stringify(crystalDialog));
    await page.screenshot({path:path.join(output,'combat-reference-crystals-phone.png')});
    await page.locator('#combat-reference-dialog [data-action=close]').click();
    await page.locator('.arena-reference-dock [data-reference=weapons]').click();
    await page.locator('#weapon-reference-attack').selectOption('Hache');
    assert.equal(await page.locator('.weapon-matchup[data-defender="Dague"] .weapon-modifier').innerText(),'+50');
    await page.screenshot({path:path.join(output,'combat-reference-weapons-phone.png')});
    await page.locator('#combat-reference-dialog [data-action=close]').click();
    await page.screenshot({path:path.join(output,'arena-phone.png')});
    await page.locator('[data-action=arena-menu]').click();
    await page.locator('#mobile-dialog [data-action=fullscreen]').click();
    await page.waitForFunction(() => document.fullscreenElement === document.documentElement);
    assert.equal(await page.locator('[data-action=exit-arena]').isVisible(), true);
    await page.screenshot({path:path.join(output,'arena-phone-immersive.png')});
    await page.locator('[data-action=exit-arena]').click();
    await page.waitForFunction(() => !document.fullscreenElement);
    // Reload into the collection with the same registry and match saved.
    await page.goto(base+'jeu/#collection');
    await page.waitForFunction(() => window.KALISTAR_READY);
    assert.equal(await page.evaluate(() => KALISTAR_DB.registry.owned('user-paris').length), count);
    await page.waitForFunction(() => [...document.images].filter(i=>i.getClientRects().length).every(i=>i.complete&&i.naturalWidth>0&&!i.src.includes('#v4-')));
    await page.screenshot({path:path.join(output,'collection-phone.png')});
    const expanded = await page.evaluate(() => structuredClone(KALISTAR_DATA));
    expanded.cards.push({...expanded.cards[0],id:'49999998',slug:'v4-49999998',origin:'published',title:'TEST ONLY'});
    await context.route(base+'jeu/catalogue.json', route => route.fulfill({json:expanded}));
    await page.reload();
    await page.waitForFunction(n => window.KALISTAR_READY && KALISTAR_DATA.cards.length===n, count+1);
    assert.equal(await page.evaluate(() => KALISTAR_DB.registry.owned('user-paris').length), count+1);
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('kalistar.v4.game')).matchId), before);
    await page.reload(); await page.waitForFunction(() => window.KALISTAR_READY);
    assert.equal(await page.evaluate(() => KALISTAR_DB.registry.owned('user-paris').length), count+1);
    await page.goto(base+'jeu/#atelier');
    await page.waitForFunction(() => window.KALISTAR_READY);
    assert.equal(await page.locator('#atelier-frame').count(),0);
    assert.equal(await page.locator('.cb-spread').count(),1);
    assert.deepEqual(errors,[]); assert.deepEqual(failures,[]);
    await context.close();
    console.log('PASS: '+count+' cards, desktop/phone, reader, PNG download, decks, arena, saved match, additive publication, no Atelier or HTTP errors: '+base);
  } finally {if(browser) await browser.close(); await new Promise(resolve => server.close(resolve));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
