'use strict';
const L=require('../../atelier/lib.cjs'),R=require('../../atelier/designer-render.cjs'),D=require('../../atelier/designer-core.cjs'),B=require('../../collaborations/nier-pilot-01/build.cjs'),T=require('../../collaborations/nier-pilot-01/typography.cjs');
const {fs,path,assert,read,write,hash,sharp,ROOT}=L;const home=__dirname,out=path.join(home,'work'),creation=path.join(ROOT,'V4/creations/43844114'),cat=path.join(ROOT,'V4/donnees/catalogue.json'),old=path.join(ROOT,'V4/expansions/2026-09-29-drebin/cards/drebin');
const file=n=>path.join(home,n),rel=f=>path.relative(ROOT,f).replaceAll('\\','/');
function files(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(d,e.name)):[path.join(d,e.name)]);}
async function guard(){await L.protectedCheck();await R.verifyAssets();for(const [f,h] of Object.entries(read(file('before.json'))))assert.equal(await hash(path.join(ROOT,f)),h,f);}
async function prepare(){assert(!fs.existsSync(file('before.json')));await L.protectedCheck();await R.verifyAssets();const observed={};for(const f of [...files(path.join(ROOT,'V4/creations')),cat])observed[rel(f)]=await hash(f);write(file('before.json'),observed);fs.cpSync(creation,file('originals'),{recursive:true});fs.copyFileSync(cat,file('catalogue-before.json'));fs.mkdirSync(path.join(out,'render'),{recursive:true});const p=read(path.join(creation,'profile.json'));assert.equal(p.atk[5],15);p.atk[5]='retry';p.visual_revision='V4-2026-09-30-drebin-clover';write(path.join(out,'profile.json'),p);const spec={...read(path.join(ROOT,'V4/expansions/2026-09-29-drebin/set.json')).cards[0],atk:p.atk};write(file('set.json'),{cards:[spec]});const donor=require('../../expansions/2026-09-27-metal-gear-mines/model.cjs').donor(spec,D);assert.equal(p.atk.filter(v=>typeof v==='number').length,3);
const plan=read(path.join(old,'render/composition.json'));for(const l of plan.layers)fs.copyFileSync(path.join(old,'render',l.file),path.join(out,'render',l.file));const effect=(await R.components(donor,{id:p.id,positionsText:true})).find(l=>l.name==='ATK D1 - effet retry');assert(effect);const name='component-clover.png';await sharp(effect.input).png().toFile(path.join(out,'render',name));plan.layers.push({file:name,name:effect.name,left:effect.left,top:effect.top,width:effect.width,height:effect.height});write(path.join(out,'render/composition.json'),plan);await sharp(await R.composite(plan.layers.map(l=>({...l,input:path.join(out,'render',l.file)})))).png().toFile(path.join(out,'render/expected-components.png'));fs.copyFileSync(path.join(creation,'illustration.png'),path.join(out,'illustration.png'));await guard();console.log('prepared');}
async function verify(){await guard();const p=read(path.join(out,'profile.json')),v=await B.verifyNative(out,p);T.verify(read(path.join(out,'render/native.json')));const delta=await L.diff(path.join(creation,'card.png'),path.join(out,'card.png'),[[110,730,201,821]]);assert.equal(delta.outside,0);assert(delta.changed>0);write(path.join(out,'verification.json'),{...v,scope:delta});await sharp(path.join(out,'card.png')).resize({width:224}).png().toFile(file('small.png'));console.log(JSON.stringify({passed:v.passed,scope:delta}));}
async function publish(){await guard();const v=read(path.join(out,'verification.json'));assert(v.passed&&v.scope.outside===0);const c=read(cat),entry=c.cards.find(c=>c.id==='43844114');entry.profile=read(path.join(out,'profile.json'));entry.nativeRevision={id:'2026-09-30-drebin-clover',proof:rel(path.join(out,'verification.json'))};const data=await require('../../atelier/game-catalog.cjs').buildCatalog({published:c.cards.filter(c=>c.kind==='created')});assert.equal(data.cards.find(c=>c.id==='43844114').atk[5],'retry');const meta=read(path.join(creation,'creation.json'));for(const n of ['profile.json','card.png','card.psd','verification.json']){meta.hashes[n]=await hash(path.join(out,n));fs.copyFileSync(path.join(out,n),path.join(creation,n));}meta.nativeRevision=entry.nativeRevision;write(path.join(creation,'creation.json'),meta);write(cat,c);const targets=['profile.json','card.png','card.psd','verification.json','creation.json'].map(n=>rel(path.join(creation,n))).concat(rel(cat));for(const [f,h] of Object.entries(read(file('before.json'))))if(!targets.includes(f))assert.equal(await hash(path.join(ROOT,f)),h,f);write(file('published.json'),{id:entry.id,hashes:meta.hashes,changed:targets});console.log('published locally');}
({prepare,verify,publish}[process.argv[2]])().catch(e=>{console.error(e);process.exitCode=1;});
