const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '../..');
const read = p => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8').replace(/^\uFEFF/, ''));
const checkOnly = process.argv.includes('--check');
const write = (name, value) => {
  const file = path.join(root, 'V3/donnees', name);
  const json = JSON.stringify(value, null, 2) + '\n';
  if(checkOnly) {
    if(fs.readFileSync(file,'utf8')!==json) throw new Error(`Generated data differs: ${name}`);
  } else fs.writeFileSync(file, json);
};
const old = read('V2/donnees/cartes.json');
const elements = read('V2/donnees/elements.json');
const weapons = Object.keys(read('V2/donnees/armes.json'));
const normalize = name => name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const style = 'Illustration verticale 3:4, peinture fantasy narrative dans la direction artistique de Momo, matieres peintes et visage expressif, sujet principal lisible, eclairage motive par le lieu, couleurs nuancees. Aucun texte, cadre, logo, symbole de carte ou interface. Anatomie lisible : deux bras, deux jambes, une tete ; pour les metamorphes, torse et posture humanoides, tete animale, details des extremites et ailes dorsales possibles ; ni corps quadrupede ni membres dupliques. ';
const sheet = row => `main/Kalistar.xlsx, Personnages ligne ${row}, via V3/sources/sources-extraites.json`;
const story = section => `V3/sources/histoire.txt, ${section}`;
elements.NONE = {id:'NONE', label:'SANS CRISTAL', strong_against:null, weak_against:null, color:'93AAA5', hue:160};

const definitions = [
  {n:1, base:1, role:3, scene:'Momo joue de sa flute dans la decharge de Chroma.', pose:'Petit robot nettoyeur sensible, seul, flute traversiere tenue horizontalement, melancolie tendre au milieu des objets abandonnes.'},
  {n:2, base:2, role:2, scene:'Cana sauve le dernier message apres la rupture du pont de Nestown.', pose:'Messagere Falco humanoide a tete de faucon, une aile repliee blessee, bras tendu avec un courrier au-dessus du vide, urgence et determination.'},
  {n:3, base:3, role:5, heal:true, guard:true, redraw:true, scene:'Julienne maintient une arche d eau sous les portes noyees de Thalassea ; scene originale conservee, illustration redessinee.', pose:'Julienne, femme Sirena adulte amphibie a deux jambes, peau turquoise nacree et fines ouies, cheveux sombres attaches, tunique de gardienne marine. Seule au premier plan, trois-quarts de profil, un genou flechi sur une marche inondee, les deux mains ecartent une arche d eau lumineuse au-dessus du passage. Visage epuise mais resolu, souffle retenu. Les silhouettes des rescapes restent petites au fond, aucun duo pose, anatomie parfaitement lisible.'},
  {n:4, base:4, role:2, scene:'Darnako retient une poutre dans sa forge pour permettre une evacuation.', pose:'Forgeron Drax humanoide a tete de dragon, deux bras et deux jambes, lame longue utilisee comme levier sous une poutre, effort physique et peur maitrisee.'},
  {n:5, base:5, role:4, scene:'Malinia retrouve une memoire emprisonnee dans la glace de Niveria.', pose:'Veilleuse humaine seule au bord du lac gele, corps penche en avant, sceptre tenu bas, expression d emerveillement grave, fissures nettes sous la glace.'},
  {n:6, base:6, role:5, heal:true, scene:'Aelis recoud la lumiere d une lanterne pour les oublies de Solaria.', pose:'Soigneuse Aurelion adulte agenouillee seule parmi les lanternes, mains fines reparant la lumiere, douceur attentive, visage distinct de Julienne.'},
  {n:7, base:7, role:1, scene:'Balmhyr enseigne la maitrise de la roche derriere sa maison de Canyonero, chapitre 8.', pose:'Vieux nain robuste, longue barbe blanche tressee, hache gravee, posture ouverte de mentor levant la roche avec une main, assurance malicieuse.'},
  {n:8, base:8, role:3, scene:'Victorvine recueille une pousse aux abords d une usine abandonnee.', pose:'Carnivert humanoide vegetal, accroupi au bord de l eau, protege une jeune pousse entre ses deux mains, concentration silencieuse, racines au decor et non membres supplementaires.'},
  {n:9, base:9, role:3, scene:'Verminia ferme la grille apres le passage des serviteurs fugitifs.', pose:'Vamp adulte a details de chauve-souris, silhouette humanoide, vue de dos trois-quarts, regard inquiet retourne vers la grille, un fil de sang tendu comme un verrou.'},
  {n:10, base:10, role:2, scene:'Zviri, assassin de Cryptown ; identite et texte de sa carte source conserves.', pose:'Tueuse Skullz adulte, un fouet identifiable, silhouette osseuse humanoide, posture basse avant le mouvement, sang-froid implacable, aucune mutilation graphique.'},
  {n:11, base:11, role:1, scene:'Nazar stabilise une berge emportee par la pluie a Zarok.', pose:'Rhinoz humanoide a tete de rhinoceros, deux mains dans la terre, pieds fermement plantes, grand effort et regard bienveillant, charrette minuscule au fond.'},
  {n:12, base:12, role:5, heal:true, guard:true, redraw:true, title:'LA PREMIERE BRECHE', job:'EVASION', source:story('Le Reveil V2, chapitre 5, evasion et lame de Xiaomi brisee, lignes 6725-6733')+' ; direction physique explicite utilisateur', scene:'Kaylis vient de briser la lame de Xiaomi avec son bras tatoue pendant l evasion de la Z13. Son pouvoir Rainbow est deja eveille ; elle avance vers la sortie, avant la Tour de Fer.', text:'La lame s est brisee contre ses tatouages. Kaylis ne comprend pas encore cette lumiere, mais elle sait a qui ouvrir le passage. Dans sa tenue noire couverte de poussiere, la Flamme de la Z13 fait son premier pas vers la liberte.', pose:'Kaylis, belle jeune femme clairement adulte de 23 ans, metissee indienne et antillaise, peau brune halee, traits delicats, corps athletique de mineuse, cheveux noirs attaches avec quelques meches libres. Tenue NOIRE fonctionnelle de mine, pantalon noir et haut noir de travail, poussiere de roche, pas robe ni armure de reine. Seule figure centrale en mouvement de sortie, torsion dynamique, un avant-bras tatoue leve devant elle ; tatouages Rainbow deja eveilles emettant une iridescence precise. Regard farouche, surprise dans les yeux, respiration courte. Barreaux ouverts et fragments d une lame au sol, galerie de la Z13 en arriere-plan. Ne pas representer Lanio mort, un trone, une resurrection ou une scene de couple.'},
  {n:13, base:13, role:1, scene:'Taulio protege ses amis dans la decharge de Chroma.', pose:'Grand robot protecteur massif, main mecanique ouverte vers le spectateur, posture stable et regard empathique, armure usee, aucun bouclier magique.'},
  {n:14, base:14, role:4, scene:'Momo anime les carillons abandonnes pour une nuit de musique.', pose:'Meme identite visuelle que Momo original, petit robot avec flute traversiere, posture dansante, joie fragile, carillons suspendus par la musique dans la decharge.'},
  {n:15, name:'SCROW', element:'AERO', race:'KORBOW', faction:'Nestown', role:4, weapon:5, job:'GUETTEUR', title:'LA FLECHE RETENUE', source:sheet(25), scene:'Scene inventee : Scrow attend sur une tour de Nestown et decide de ne pas tirer sur un messager.', text:'Scrow reconnait le sceau avant de lacher la corde. Il laisse le messager franchir les toits. Une fleche retenue peut peser autant qu une fleche tiree.', pose:'Korbow adulte humanoide a tete de corbeau, bec sombre, mantelet gris clair, deux bras tenant un arc, deux jambes sur un parapet, ailes dorsales repliees. Profil serre, corde relachee, doute lucide, ville aerienne de Nestown.'},
  {n:16, name:'NERIS', element:'CRYO', race:'HUMAIN', faction:'Niveria', role:5, weapon:14, heal:true, job:'SOIGNEUSE', title:'LE POULS SOUS LA GLACE', source:'Creation V3 ; Niveria et cristal CRYO issus du repertoire V2', scene:'Scene inventee : Neris chauffe un abri de secours en isolant la tempete par une paroi de givre.', text:'Neris ferme la tempete derriere une paroi de givre. Dans l abri, les couvertures sont pretes. Elle compte les souffles jusqu a ne plus entendre que le vent dehors.', pose:'Soigneuse humaine adulte d une cinquantaine d annees, visage rond, cheveux gris courts, lunettes rondes, manteau prune et blanc. Vue de face a hauteur de poitrine, mains autour d un orbe de glace translucide, expression rassurante et fatigue reelle, abri de montagne et lits vides derriere.'},
  {n:17, name:'ILIANE', element:'LUXO', race:'AURELION', faction:'Solaria', role:4, weapon:13, job:'ARCHIVISTE', title:'LE NOM RETROUVE', source:'Creation V3 ; Aurelion et Solaria issus du repertoire V2', scene:'Scene inventee : Iliane revele les noms effaces d une archive de Solaria.', text:'Iliane eclaire les pages que le conseil voulait oublier. Lettre apres lettre, les noms reviennent. Elle ne baisse plus les yeux quand la porte s ouvre.', pose:'Aurelion adulte a peau cristallisee lumineuse, visage anguleux androgyne, crane rase, robe rouge et ivoire, debout de trois-quarts avec un tome ouvert. Une main montre un nom efface sans texte lisible, calme indocile, rayonnages de pierre blanche.'},
  {n:18, base:18, role:2, scene:'Lok bloque un convoi dans la fonderie ; vignette V2 inventee conservee, sans en faire un episode canonique.', pose:'Nain aux cheveux noirs et barbe courte, main sur un levier de fonderie, marteau au cote, orgueil inquiet, cadrage serre, scene V2 conservee.'},
  {n:19, base:19, role:1, scene:'Belrog redresse le signal du col ; scene originale V2 conservee.', pose:'Rhinoz humanoide vieillissant a tete de rhinoceros, masse de voyage, deux bras relevant un signal de col, poussiere et attente patiente, deux jambes robustes.'},
  {n:20, name:'SERAPHINA', element:'HEMATO', race:'VAMP', faction:'Draevenheim', role:5, weapon:6, guard:true, job:'MEDIATRICE', title:'LE SERMENT SUSPENDU', source:sheet(44)+' ; race, faction et scene proposes V3', scene:'Scene inventee : Seraphina suspend un sceau de dette plutot que de l executer.', text:'Seraphina laisse le sceau se dissoudre entre ses doigts. Pour une nuit, aucune dette de sang ne franchira cette porte. Demain, elle devra repondre de ce repit.', pose:'Femme Vamp adulte aux traits matures, oreilles de chauve-souris discretes, cheveux argent courts, manteau vert sombre. Assise seule a une longue table, fouet fin enroule a la ceinture, main ouverte au-dessus d un sceau rouge qui se defait, compassion retenue et regard ferme.'},
  {n:21, name:'LANIO', element:'NONE', race:'HUMAIN', faction:'Z13', role:3, weapon:8, job:'JOUEUR D ASTRABALL', title:'LE BLONDINET DE ZAROK', source:sheet(11)+' ; '+story('chapitres 10-12, Astraball a Zarok ; Le Reveil V2 chapitre 1'), scene:'Lanio joue a l Astraball chez les Rhinoz de Zarok, sans cristal. Il reste humain ; les Rhinoz sont ses partenaires et adversaires.', text:'Lanio a enfin une vraie balle entre les mains. Sur le terrain de Zarok, le blondinet improvise un crochet et rit avant meme de savoir s il passera. Pour quelques minutes, la Z13 parait tres loin.', pose:'Beau jeune HOMME HUMAIN clairement adulte, 21 ans, cheveux BLONDS dores, sourire ravageur joyeux, silhouette fine et sportive. Pivot acrobatique lisible sur le terrain d Astraball de Zarok, une main protege le ballon, une jambe en appui et l autre levee. Partenaires Rhinoz humanoides a tete de rhinoceros en arriere-plan uniquement, gradins dans la roche. Sa lance double-lame repose hors du jeu contre la barriere. PAS tete animale sur Lanio, pas cristal, pas pouvoir ni halo ; mouvement athletique naturel.'},
  {n:22, name:'MALABA', aliases:['Baba'], element:'NONE', race:'HUMAIN', faction:'Z13', role:1, weapon:3, job:'MINEUR', title:'UNE PLACE AU COMPTOIR', source:sheet(12)+' ; '+story('Le Reveil V2, chapitre 1, La Gueule Fumante, lignes 6289-6294'), scene:'Malaba, dit Baba, au bar de La Gueule Fumante au debut du recit, avant toute fusion.', text:'Baba pousse sa ration vers la place vide et plaisante avec la salle. Ses epaules occupent presque tout le comptoir. Pourtant, a la Gueule Fumante, personne ne sait faire autant de place aux autres.', pose:'Malaba surnomme Baba, homme humain adulte massif tres baraque, immenses epaules et mains calleuses, yeux bruns chaleureux, visage humain doux, vetements de mineur uses. Assis de biais au comptoir de La Gueule Fumante, grand sourire bon enfant, il pousse une assiette de pain vers une place vide. Bras et carrure puissants, ambiance de bar populaire souterrain debut du recit ; personne a secourir dans les bras, aucun duo pose, aucun cristal, aucune pierre integree au corps, aucun halo.'},
  {n:23, name:'GEN', element:'NONE', race:'CYBORG', faction:'Z13', role:4, weapon:9, job:'MECANICIEN', title:'AVANT L ETINCELLE', source:sheet(15)+' ; '+story('Le Reveil V2 chapitre 1, bras gauche et meche verte, lignes 6297-6299 ; chapitre 4 atelier avant transfusion'), scene:'Vignette de Gen reparant son bras gauche dans l atelier improvise, AVANT la transfusion Electro du chapitre 4.', text:'Gen bloque le petit engrenage entre ses doigts et reprend l ajustement. Dans cet atelier fait de recuperation, son bras gauche reste une mecanique imparfaite. Il n y a pas encore d eclair, seulement une idee qui refuse de ceder.', pose:'Gen, jeune homme adulte plutot petit et mince, yeux sombres attentifs, cheveux noirs soigneusement peignes avec UNE meche vert emeraude. Assis seul a son etabli de recuperation dans la Z13, penche avec concentration, main DROITE organique tenant un petit tournevis et reparant son propre bras GAUCHE partiellement mecanique, qui reste attache a son epaule. Exactement deux bras, deux jambes, pas de bras de rechange ressemblant a un membre vivant. Pieces, cables, lampe de travail ; leger sourire d une solution trouvee. Prothese rudimentaire, avant fusion, sans cristal, aucun arc electrique, aucun halo, aucune barriere magique.'},
  {n:24, name:'MAGNAR', element:'MINERO', race:'GOLEM', faction:'Durane', role:1, weapon:2, job:'GEOLIER', title:'LA PORTE DE PIERRE', source:sheet(6)+' ; '+story('chapitre 5, Gen et Magnar'), scene:'Magnar garde seul un passage etroit de la Z13, juste avant l affrontement avec Gen.', text:'Magnar avance d un pas et la galerie semble retrecir. Il n a pas besoin de hausser la voix. La roche de son corps connait chaque vibration de la mine.', pose:'Golem humanoide colossal de granit, silhouette humaine deux bras deux jambes, fissures minerales fines, masse de pierre tenue basse. Contre-plongee au seuil d une galerie, calme menacant, epaules presque au plafond, aucun autre personnage principal.'},
  {n:25, name:'KOGNUS', element:'NONE', race:'NAIN', faction:'Z13', role:2, weapon:15, job:'SURVEILLANT', title:'LES CLES DU SERVICE', source:sheet(7)+' ; '+story('chapitres 1 et 5, Kognus nain et dague')+' ; absence de cristal attribuee par prudence', scene:'Vignette inventee de Kognus comptant les cles avant sa ronde dans la Z13.', text:'Kognus recompte les cles dans sa paume. Il reconnait chaque porte au bruit de la serrure. Celle qui reste silencieuse l inquiete davantage que les autres.', pose:'Nain adulte trapu, traits burines, sourcils epais, barbe rousse courte, veste grise de surveillance. Gros plan en trois-quarts sur le trousseau dans sa main, autre main pres d une dague, nervosite dissimulee, pas de cristal ni halo.'},
  {n:26, name:'REEVUS', aliases:['Revuus'], element:'NONE', race:'NAIN', faction:'Z13', role:3, weapon:4, job:'INTENDANT', title:'LE REGISTRE DES ABSENTS', source:sheet(8)+' ; '+story('chapitre 7, Reevus charge de la Z13 ; variante Revuus au chapitre 1'), scene:'Vignette inventee : Reevus seul a la Z13 apres le depart de Voloden, devant le registre des travailleurs.', text:'Reevus decouvre plus de blancs que de noms dans le registre. Il referme le livre d un geste sec. Les absents commencent a prendre plus de place que les ordres.', pose:'Nain adulte au visage long, barbe grise en deux tresses, lunettes sur le front, habit de service vert, debout devant une table trop haute. Il ferme un registre sans texte lisible, fleau court pose pres du mur, humeur irritee et fatiguee, aucun cristal ou aura.'},
  {n:27, name:'XIAOMI', element:'NONE', race:'HUMAIN', faction:'Z13', role:2, weapon:18, job:'DUELLISTE', title:'UNE SECONDE D HESITATION', source:sheet(9)+' ; '+story('chapitre 5, katana brise et hesitation')+' ; race humaine et NONE proposes sans transfusion attestee', scene:'Xiaomi observe le katana brise apres l intervention de Kaylis, sans pouvoir personnel affirme.', text:'Xiaomi examine la cassure nette. Pour la premiere fois, la precision de sa lame ne lui explique rien. Elle recule d un pas, et ce pas lui pese.', pose:'Guerriere humaine adulte elancee, cheveux noirs en chignon haut, manteau sombre ample, debout seule de profil dans un couloir. Elle tient un katana casse a distance de son visage, surprise contenue qui fissure son assurance, aucune magie personnelle ni halo.'},
  {n:28, name:'VOLODEN', element:'NECRO', race:'CARDEMORTIS', faction:'Z13', role:2, weapon:19, job:'DIRIGEANT', title:'LE SIEGE VACANT', source:sheet(10)+' ; '+story('chapitre 16, retour de Voloden au siege Z13 ; Le Reveil V2 description'), scene:'Voloden reprend le siege de la Z13 au Conseil des Zones. Scene canonique, cadrage individuel.', text:'Voloden pose sa lettre de nomination devant le siege vide. Sa voix ne monte pas. Autour de la table, les autres comprennent deja qu il ne demande pas la permission.', pose:'Homme Cardemortis grand et imposant, peau blanc nacre presque translucide, longs cheveux d argent, yeux glacials, manteau noir austere. Assis tres droit sur le siege du conseil, mains croisees, faux ceremonielle appuyee a cote, sourire infime, menace politique calme et non attaque spectaculaire.'},
  {n:29, name:'THANOR', element:'PYRO', race:'DRAX', faction:'Vulkar', role:2, weapon:17, job:'CHEF DE FORGE', title:'LA COURONNE REFROIDIE', source:sheet(20)+' ; scene et fonction locale proposes V3, titre Le Roi Dragon du classeur non impose comme souverain global', scene:'Scene inventee : Thanor depose une couronne de cerement a la forge de Vulkar.', text:'Thanor pose la couronne encore chaude sur l enclume. Le metal garde l empreinte de ses doigts. Ce soir, il prefere le bruit du marteau aux acclamations.', pose:'Drax adulte humanoide a tete de dragon rouge sombre, petites cornes abimees, deux bras deux jambes, tablier de forge ceremonial. Debout penche sur une enclume, une main depose une couronne de metal, epee longue au dos, fierte lasse, aucun dragon quadrupede.'},
  {n:30, name:'DARUK', element:'PYRO', race:'DRAX', faction:'Vulkar', role:1, weapon:0, job:'REMPART', title:'LE PONT DES BRAISES', source:sheet(33)+' ; scene proposee V3', scene:'Scene inventee : Daruk ferme une vanne de lave au bout d un pont de Vulkar.', text:'Daruk tourne la roue jusqu a sentir le metal gemir. Le courant de lave ralentit sous le pont. Il attend que la derniere passerelle cesse de trembler avant de retirer sa main.', pose:'Drax humanoide robuste a tete de dragon aux ecailles claires et cornes courtes, exactement deux bras deux jambes. Vue laterale plein corps, il pousse une grande roue de vanne, hache accrochee a la taille, effort obstine et sueur, lave confinee sous un pont de basalte.'},
  {n:31, name:'POLUX', element:'PYRO', race:'FELINEUS', faction:'Vulkar', role:5, weapon:10, heal:true, job:'SOIGNEUR', title:'LA CHALEUR QUI RESTE', source:sheet(34)+' ; faction et scene proposees V3', scene:'Scene inventee : Polux entretient des compresses chaudes dans un dispensaire de Vulkar.', text:'Polux rechauffe les linges sans les bruler. Il ecoute la respiration derriere le rideau. Le feu, entre ses mains, sait aussi parler doucement.', pose:'Felineus adulte humanoide a tete de lynx couleur gris cendre, touffes aux oreilles, deux mains et deux pieds, pas pattes de quadrupede. Soigneur en tablier blanc et vert, assis seul, baton au cote, chauffe des compresses dans ses paumes avec une flamme minuscule, douceur serieuse, dispensaire sobre.'},
  {n:32, name:'JELLY-JOE', element:'ELECTRO', race:'TANTALAK', faction:'Crabazar', role:5, weapon:8, guard:true, job:'MERCENAIRE', title:'LE CONTRAT RATURE', source:sheet(30)+' ; alias Tentalak dans TribuHybride Animals ; scene proposee V3', scene:'Scene inventee : Jelly-Joe refuse de laisser un quai de Crabazar sans protection.', text:'Jelly-Joe rature l heure de depart. Tant que le dernier bac n a pas quitte le quai, son contrat continue. Le client proteste ; il peut attendre.', pose:'Tantalak adulte humanoide amphibie a tete de meduse translucide compacte, torse vetu et exactement deux bras et deux jambes ; filaments courts uniquement comme details de tete, aucun bras-tentacule supplementaire. Mercenaire en ciré jaune desature, une botte sur une bitte d amarrage, lance droite dans une main, sourire goguenard, leger reflet Electro dans une lanterne de quai.'},
  {n:33, name:'BLOOM', element:'HERBO', race:'TOXINAR', faction:'Arborium', role:4, weapon:14, job:'BOTANISTE', title:'LA GRAINE SOUS SCELLES', source:sheet(42)+' ; faction et scene proposees V3', scene:'Scene inventee : Bloom examine une semence toxique dans la serre d Arborium.', text:'Bloom tourne la graine sous le verre. La fleur qu elle promet pourrait sauver la serre ou l etouffer. Il prend le temps d apprendre la difference.', pose:'Toxinar vegetal humanoide adulte, tete florale ramassee avec visage lisible, peau verte et petales pourpres courts, deux bras deux jambes. Debout courbe devant un orbe de verre contenant une graine, pince dans une main, curiosite prudente, serre blanche eclairee par un matin net.'},
  {n:34, name:'VALAZAR', element:'NECRO', race:'SKULLZ', faction:'Cryptown', role:4, weapon:12, job:'NECROMANCIEN', title:'LE NOM DANS LA CENDRE', source:sheet(45)+' ; scene et arme proposees V3', scene:'Scene inventee : Valazar reconstitue une inscription funeraire effacee dans Cryptown.', text:'Valazar suit du doigt une ligne de cendre. Il ne cherche pas a rappeler le mort, seulement son nom. Meme Cryptown a des oublis qu il refuse.', pose:'Skullz adulte au crane fin, robe de cendres gris et rouge, un sceptre simple. Agenouille seul devant une plaque brisee sans texte lisible, geste minutieux avec une main osseuse, recueillement severe, lumiere de veilleuse et magie sombre limitee a la cendre.'},
  {n:35, name:'CAPITAINE SKULLY', element:'NECRO', race:'SKULLZ', faction:'Cryptown', role:3, weapon:16, job:'CAPITAINE', title:'LE DERNIER AMARRAGE', source:sheet(47)+' ; contradiction classe Middle / pos 2 tranchee vers P3, scene proposee V3', scene:'Scene inventee : le capitaine Skully ramene seul son navire a quai.', text:'Skully enroule la derniere aussiere autour du bollard. Le bateau tient enfin. Avant de descendre, il salue le pont vide avec le serieux d un capitaine devant tout son equipage.', pose:'Capitaine Skullz adulte, crane large use, tricorne de toile bleu petrole, manteau maritime vert, epee courte a la ceinture. Debout sur un quai, un bras tire une corde, l autre salue, fierte nostalgique et humour discret, bateau ancien entier visible au fond.'},
  {n:36, name:'ELENION', element:'GEO', race:'CERELF', faction:'Woodland', role:3, weapon:4, job:'ARPENTEUR', title:'LA LISIERE DEPLACEE', source:sheet(48)+' ; cristal Terre conserve malgre HERBO dans la table generique des Cerelf ; scene proposee V3', scene:'Scene inventee : Elenion releve une borne de Woodland deracinee par la crue.', text:'Elenion retrouve la borne loin du chemin. La foret n a pas efface la limite ; la riviere l a deplacee. Il prend une nouvelle mesure avant de juger les traces.', pose:'Cerelf adulte humanoide a tete de cerf, bois courts asymetriques, deux bras humains et deux jambes vetues, tunique verte et rouge. Agenouille sur un seul genou pres d une borne, fleau de marche pose au sol, regard mesure et pensif, clairiere humide.'},
  {n:37, name:'YVAR', element:'GEO', race:'RHINOZ', faction:'Zarok', role:3, weapon:8, job:'ECLAIREUR', title:'LA ROUTE SOUS LE SABLE', source:sheet(4)+' ; '+story('chapitres 10 et 15, Yvar fils de Koronak, lance et route d infiltration')+' ; cristal GEO et scene proposes V3', scene:'Yvar reconnait le canal asseche avant la mission de sauvetage de Gen ; instant de preparation extrapole du chapitre 15.', text:'Yvar descend dans le canal et ecoute le sable sous ses pas. Il retrouve le passage sans allumer sa lampe. Ceux qui le suivent n auront pas besoin de connaitre tous ses detours.', pose:'Rhinoz humanoide adulte a tete de rhinoceros, corne courte marquee d une rayure, armure legere verte, lance gravee. Plein corps vu en leger plongee, accroupi au bord d un canal asseche et montrant une piste, vigilance tranquille, pas de corps animal.'},
  {n:38, name:'GILMARR', element:'AERO', race:'RHINOZ', faction:'Zarok', role:1, weapon:3, job:'PILIER D ASTRABALL', title:'LA PLACE DANS L EQUIPE', source:sheet(3)+' ; '+story('chapitre 11, rencontre de Gilmarr sur le terrain')+' ; role pilier et cristal AERO inventes, Sentry aerien anonyme non identifie a Gilmarr par le recit', scene:'Gilmarr accueille Lanio sur le terrain. Pose individuelle et specialisation AERO proposees V3.', text:'Gilmarr decale le plot de la ligne et fait signe d entrer. Une place vient de s ouvrir dans l equipe. Son sourire promet un match difficile, pas une faveur.', pose:'Jeune adulte Rhinoz humanoide a tete de rhinoceros, carrure de pilier sportif, maillot vert bouteille et blanc, deux bras deux jambes. Debout bras ouvert invitant a entrer, autre main tient un plot, sourire confiant, anneaux d Astraball derriere, souffle AERO discret soulevant la poussiere et non une boule magique.'},
  {n:39, name:'RUBY', element:'HYDRO', race:'SIRENA', faction:'Thalassea', role:4, weapon:7, job:'CARTOGRAPHE', title:'LA CARTE DES COURANTS', source:'main/Kalistar.xlsx, Pull1 Carte A85 et AA85 (Ruby, HYDRO, Sirenas) ; faction, arme et scene proposees V3', scene:'Scene inventee : Ruby cartographie les courants depuis un phare de Thalassea.', text:'Ruby incline son instrument vers la passe. Les filets d eau dessinent une route que la carte n avait jamais montree. Elle sourit : le retour sera plus court.', pose:'Sirena adulte amphibie a peau bleu profond, fines ouies, cheveux rouges attaches, deux jambes en bottes de pont. Debout seule dans un phare ouvert, pistolet hydrographique categorie Gun et carte sans ecriture lisible sur la table, lignes d eau fines forment un releve, enthousiasme methodique.'},
  {n:40, name:'SORYN', element:'AERO', race:'FALCO', faction:'Nestown', role:4, weapon:11, job:'ACCORDEUR', title:'LE VENT JUSTE', source:'Creation V3 ; race Falco et faction Nestown issues du repertoire V2', scene:'Scene inventee : Soryn accorde les cloches de brume des ponts de Nestown.', text:'Soryn attend que le vent tourne avant de toucher la corde. Une note traverse le brouillard. Sur le pont invisible, les voyageurs savent de nouveau ou poser le pied.', pose:'Falco humanoide adulte a tete de faucon claire, petites plumes rousses, ailes dorsales repliees distinctes des deux bras. Assis sur une traverse stable, deux pieds visibles, pince les cordes d une cithare portable, yeux mi-clos de concentration heureuse, cloches et ponts suspendus dans un brouillard lumineux.'},
  {n:41, name:'THALIE', element:'HERBO', race:'CARNIVERT', faction:'Arborium', role:5, weapon:13, heal:true, job:'HERBORISTE', title:'CE QUI REPOUSSE', source:'Creation V3 ; Carnivert et Arborium issus du repertoire V2', scene:'Scene inventee : Thalie consigne la reprise d une foret apres un incendie.', text:'Thalie tourne la page couverte de suie et pose une feuille neuve entre les feuillets. La foret ne reprend pas tout d un coup. Elle commence ici.', pose:'Carnivert humanoide adulte au visage vegetal ovale et expressif, coiffure de feuilles courtes, peau vert sombre, habit de voyage blanc et corail. Assise en tailleur sur un tronc, deux mains dans un herbier ouvert, sourire de soulagement, jeunes pousses clairement visibles parmi des troncs brules, aucune silhouette secondaire principale.'}
];

const max = {1:{atk:[210,175,140,105,70,35], defense:[300,250,200,150,100,50]}, 2:{atk:[300,250,200,150,100,50], defense:[180,150,120,90,60,30]}, 3:{atk:[240,200,160,120,80,40], defense:[240,200,160,120,80,40]}, 4:{atk:[300,250,200,150,100,50], defense:[180,150,120,90,60,30]}, 5:{atk:[180,150,120,90,60,30], defense:[210,175,140,105,70,35]}};
const specials = {
  1:{atk:{2:'retry',4:'mana'},defense:{2:'retry'}}, 3:{atk:{4:'guard',5:'revive'}},
  6:{atk:{5:'revive'}},7:{atk:{4:'guard'}},9:{defense:{2:'dodge'}},10:{atk:{2:'death'},defense:{0:'dodge'}},
  11:{atk:{4:'guard'}},12:{atk:{4:'guard',5:'revive'},defense:{5:'retry'}},
  13:{atk:{4:'guard',5:'buff_atk'}},14:{atk:{3:'retry',5:'mana'}},
  16:{atk:{5:'revive',4:'mana'}},19:{atk:{4:'guard'}},20:{atk:{4:'guard',5:'retry'}},
  21:{defense:{2:'dodge'}},22:{atk:{4:'guard',5:'buff_atk'}},
  24:{atk:{4:'guard'}},25:{defense:{5:'retry'}},26:{atk:{5:'buff_atk'}},27:{defense:{3:'dodge'}},
  28:{atk:{0:'death'}},30:{atk:{4:'guard'}},31:{atk:{4:'revive'}},
  32:{atk:{1:'mana',3:'buff_atk',5:'guard'}},34:{atk:{0:'death'}},
  35:{atk:{3:'retry'}},38:{atk:{4:'guard'}},40:{atk:{5:'mana'}},41:{atk:{4:'retry',5:'revive'}}
};
const magicDice = {1:[6,5,3,1],2:[3],3:[6,5,4,3],4:[6,4],5:[6,5,4,3,2,1],6:[6,5,4,3,2],7:[6,4],8:[6,4,2],9:[6,5,3],10:[],11:[6,3],12:[6,5,4,3],13:[],14:[6,5,4,2],15:[],16:[6,5,4,3],17:[6,5,4,3,2,1],18:[6],19:[6,3],20:[6,4,3],24:[6,3],28:[5],29:[6,3],30:[6,4],31:[6,5,4,3,1],32:[6,4,2],33:[6,5,4,3,2,1],34:[5,4,3,2,1],35:[6,3],36:[6,4,2],37:[6,3],38:[6,3],39:[6,5,4,3,2,1],40:[6,5,4,3,2],41:[6,5,4,3]};

const cards = definitions.map(d => {
  const b = d.base ? structuredClone(old[d.base-1]) : {};
  const id = String(30000000+d.n);
  const element = d.element || b.element;
  const name = d.name || b.name;
  const slug = d.base ? b.slug : `${String(d.n).padStart(2,'0')}_${element}_${name.replace(/[^A-Z0-9]+/g,'_')}`;
  const role = d.role;
  const canGuard = role===1 || !!d.guard;
  const canHeal = !!d.heal;
  const panels = {};
  // Start each face within the role's spreadsheet interval, then replace selected faces with actions.
  for(const stat of ['atk','defense']) {
    panels[stat] = max[role][stat].map((v,i)=>v-4-((d.n*3+i*2+(stat==='defense'?5:0))%7));
    for(const [i,effect] of Object.entries(specials[d.n]?.[stat] || {})) panels[stat][i] = effect;
  }
  if(d.n===1) { panels.atk=[202,167,'retry',84,'mana',29]; panels.defense=[200,167,'retry',100,59,11]; }
  const source = d.source || `${b.source} ; V2/donnees/cartes.json ${b.id} ; scene conservee, profil reequilibre V3`;
  const copy = !!d.base && !d.redraw;
  const magic = (magicDice[d.n] || []).filter(die=>element!=='NONE' && typeof panels.atk[6-die]==='number');
  const barriers = element==='NONE' ? [] : (b.barriers || (role===5?[6,3]:role===1?[5,2]:[4])).filter(die=>typeof panels.defense[6-die]==='number');
  const c = {
    element, name, race:d.race||b.race, faction:d.faction||b.faction,
    job:d.job||b.job, title:d.title||b.title,
    positions:d.n===1||d.n===14?[3,4]:[role], weapon:d.weapon===undefined?b.weapon:weapons[d.weapon],
    ...panels, magic, barriers, text:d.text||b.text,
    source, color:elements[element].color, hue:elements[element].hue,
    advantage:element==='RAINBOW'?40:element==='NONE'?0:(b.advantage??30),
    disadvantage:element==='NONE'||element==='RAINBOW'?0:(b.disadvantage??30),
    id, slug, art:`V3/assets/illustrations/${slug}.png`, reference:null,
    weapon_index:d.weapon===undefined?b.weapon_index:d.weapon,
    visual_revision:'V3-repertoire-41', barcode_style:'spectrum_dark',
    characterId:normalize(name), role, sentry:element!=='NONE', canGuard, canHeal,
    story_scene:d.scene, prompt:style+d.pose+(element==='NONE'?' Sans cristal : aucun halo ni barriere elementaire.':''),
    source_art:copy?b.art:null, art_action:copy?'copy':d.redraw?'redraw':'generate',
    previous_id:d.base?b.id:null,
    replaces_v2_id:[15,16,17,20].includes(d.n)?String(d.n).padStart(8,'0'):null,
    aliases:d.aliases||[],
    balance_source:'main/Kalistar.xlsx, Capacite base ; ajustements V3 decrits dans DECISIONS_NARRATIVES.md'
  };
  return c;
});

const sceneRevisions=read('V3/donnees/revision_buffs_scenes_profils.json');
for(const c of cards){
  const revision=sceneRevisions[c.id];if(!revision)continue;
  const {pose,...fields}=revision;
  Object.assign(c,fields);
  c.prompt='Peinture narrative Kalistar, reference Momo ; touches visibles, matieres usees, anatomie lisible, emotion. Aucun texte, cadre ou interface. '+pose;
  c.visual_revision='V3-buffs-scenes-20260914';
  c.source+=' ; revision de scene explicite utilisateur 2026-09-14';
  c.art_action='redraw';c.source_art=null;
}

const arenaDefinitions = [
  ['aero','Les ponts de Nestown','Passerelles et cloches au-dessus des nuages','AERO',['cana','scrow','soryn'],'V2 Nestown ; architecture du Guide complet des mondes, scene de lieu proposee V3'],
  ['hydro','Les portes de Thalassea','Arches immergees et bassin des marees','HYDRO',['julienne','ruby'],'V2 Thalassea ; Guide complet des mondes, region Eau ; lieu de Julienne extrapole'],
  ['electro','La decharge de Chroma','Carillons oublies et rails conducteurs','ELECTRO',['momo','taulio'],'V2 Momo et Taulio ; faction Chroma conservee selon confirmation utilisateur V2'],
  ['pyro','La grande forge de Vulkar','Ponts de basalte et vannes de lave','PYRO',['darnako','thanor','daruk','polux'],'Classeur Vulkar et Guide complet des mondes, region Feu ; aire de combat proposee'],
  ['cryo','Le lac de Niveria','Memoires sous le givre','CRYO',['malinia','neris'],'V2 Niveria ; extension originale du lieu de Malinia'],
  ['luxo','Le sanctuaire de Solaria','Lanternes et archives de lumiere','LUXO',['aelis','iliane'],'V2 Solaria ; Guide complet des mondes, region Lumiere'],
  ['minero','Les terrasses de Canyonero','La pierre et le minerai de Durane','MINERO',['balmhyr','lok','magnar'],'Histoire chapitres 7-10 et Guide complet des mondes ; aire de combat proposee'],
  ['herbo','La serre d Arborium','Racines anciennes et nouvelles pousses','HERBO',['victorvine','bloom','thalie'],'V2 Arborium ; Guide complet des mondes, region Plante ; serre proposee'],
  ['hemato','Les grilles de Draevenheim','Le passage des serments','HEMATO',['verminia','seraphina'],'V2 Draevenheim ; Guide complet des mondes, region Sang'],
  ['necro','Le quai de Cryptown','Cendres et dernier amarrage','NECRO',['zviri','valazar','capitaine-skully'],'Classeur Cryptown ; quai invente pour la scene de Skully'],
  ['geo','Les remparts de Zarok','Routes et canaux du peuple Rhinoz','GEO',['nazar','belrog','yvar','gilmarr'],'Histoire chapitre 10, village de Zarok ; affinites de jeu proposees'],
  ['rainbow','Le seuil du Temple','La lumiere des douze cristaux','RAINBOW',['kaylis'],'Classeur Ville, Temple et Rainbow ; lieu et affinite Kaylis symboliques inventes, pas un voyage canonique'],
  ['z13','La Gueule Fumante','Un refuge au fond de la mine',null,['kaylis','lanio','malaba','gen','kognus','reevus','xiaomi','voloden'],'Histoire Le Reveil V2, chapitre 1, La Gueule Fumante et Z13 ; lieu sans bonus de cristal'],
  ['trone-fer','Le Trone de Fer','Le Conseil des Zones',null,['balmhyr','lok','voloden'],'Histoire chapitres 16-17, Tour de Fer et Conseil ; titre de lieu de jeu Trone de Fer'],
  ['astraball','Le terrain de Zarok','La place dans l equipe',null,['lanio','gilmarr','nazar'],'Histoire chapitres 10-12, Astraball a Zarok ; affinite Nazar, hote local, proposee'],
  ['ruins','Les ruines silencieuses','Terrain neutre',null,[],'Terrain de test invente V3, aucun bonus']
];
const arenas = arenaDefinitions.map(([id,name,subtitle,element,homeCharacters,source])=>({id,name,subtitle,image:`assets/arenas/${id}.webp`,element,elementBonus:element?15:0,homeCharacters,homeAttack:homeCharacters.length?10:0,homeDefense:homeCharacters.length?10:0,source}));
const arenaStyle = 'Peinture fantasy narrative coherente avec les illustrations de Momo et les cartes Kalistar. Image horizontale 16:9, decor de combat sans personnage, sans texte, sans logo, sans cadre, sans cartes ni interface. Perspective architecturale lisible, espace central praticable degage, premier plan stable avec deux approches laterales de poids visuel comparable. Details du lieu reconnaissables, eclairage lisible et profondeur naturelle, pas de brouillard opaque ni flou general, pas d explosion au centre. ';
const arenaScenes = {
  aero:{anchor:'TOME 5 - ALTITIA',section:'Guide complet des mondes, tome 5, Architecture & Climat',status:'adaptation',scene:'Esplanade de Nestown reliee a des ponts suspendus et a des tours de guet ; composition inventee a partir de V2 et de l architecture aerienne du guide.',prompt:'Les ponts de Nestown : large esplanade de pierre claire et metal patine au-dessus des nuages, garde-corps fins, ponts suspendus conduisant aux tours de guet a plusieurs niveaux. Cloches de brume suspendues sur les bords, petits cristaux AERO vert menthe enchasses dans les balises. Ciel de matin bleu pale, ombres nettes, voiles tendues par le vent, accents rouges sur cordages. Sol central libre, horizon aerien, aucune silhouette volante.'},
  hydro:{anchor:'TOME 4 -',section:'Guide complet des mondes, tome 4, Architecture & Climat',status:'adaptation',scene:'Portes noyees de Thalassea, derivees de la vignette de Julienne V2 et des architectures amphibies du guide.',prompt:'Les portes de Thalassea : vaste bassin de maree borde d arches de nacre et de corail vivant, marches de pierre descendantes, passage central emerge tres peu profond. Murs immerges visibles sous une eau turquoise transparente, ecluses laterales ouvertes sur la mer, cristaux HYDRO cyan dans les piliers. Lumiere diurne filtree par l eau, reflets naturels et coquilles bordeaux. Pas de vague geante ni de personnage ; deux rives utilisables et sol central clairement visible.'},
  electro:{anchor:'TOME 2 - VOLTANIA',section:'Guide complet des mondes, tome 2, Architecture & Climat ; cartes V2 Momo et Taulio',status:'adaptation',scene:'Decharge de Chroma des deux robots V2, mise en scene inventee ; ne pas renommer leur faction en Voltania.',prompt:'La decharge de Chroma : cour ouverte entre des piles organisees de machines anciennes, rails conducteurs incrustes dans le sol, petits carillons de recuperation suspendus aux poutres. Au fond, tours conductrices et reseaux electriques visibles, pas de grand ecran publicitaire. Cristaux ELECTRO jaune clair dans des bornes laterales ; acier patine, morceaux de peinture rouge et vert, lumiere de fin d apres-midi douce. Passage central degage, quelques fleurs dans les interstices, aucune machine humanoide active, aucun robot personnage.'},
  pyro:{anchor:'TOME 3 - PYROTHIA',section:'Guide complet des mondes, tome 3, Architecture & Climat ; classeur Ville Vulkar',status:'adaptation',scene:'Plateforme de forge de Vulkar, au-dessus de canaux de lave ; emplacement precis invente.',prompt:'La grande forge de Vulkar : plateforme immense de basalte et de fer entre deux vannes de lave, ponts metalliques et grandes enclumes sur les bords, forge titanesque dans un cratere ouvert au ciel. Lave rouge-orange confinee dans des canaux en contrebas, cristaux PYRO rouges dans les verrous, vapeur blanche ponctuelle. Lumiere du jour gris clair entrant par la toiture ouverte, acier bleute, materiaux nets ; aucun incendie de surface, sol praticable sombre au centre, pas de personnage.'},
  cryo:{anchor:'TOME 11 - GLACIALIS',section:'Guide complet des mondes, tome 11, Architecture & Climat ; carte V2 Malinia',status:'adaptation',scene:'Plateau du lac de Niveria, rive et memoires gelees de Malinia ; emplacement invente dans le biome du guide.',prompt:'Le lac de Niveria : large plateau de glace solide au premier plan, petites fractures sous la surface laissant voir de vieilles pierres et des bulles immobiles, aucun personnage emprisonne. Palais de glace et ponts de givre sur les rives, cristaux CRYO bleu pale dans des bornes et sapins sombres aux extremites. Matin clair, neige blanche, reflets turquoise et tissus rouges sur les balises, ciel froid sans aurore envahissante. Le centre reste plat, securisant et ouvert.'},
  luxo:{anchor:'TOME 7 - SOLARIA',section:'Guide complet des mondes, tome 7, Architecture & Climat ; carte V2 Aelis',status:'adaptation',scene:'Sanctuaire de Solaria, lanternes d Aelis et archives d Iliane ; architecture du guide, salle precise inventee.',prompt:'Le sanctuaire de Solaria : grande nef de cristal et pierre blanche, prismes verticaux, lanternes reparees et rayonnages d archives sur les murs lateraux. Escalier de lumiere solidifiee visible au fond, fontaines de lumiere liquide discretes, cristaux LUXO ivoire enchasses dans les colonnes. Lumiere blanche chaleureuse, fines refractions colorees locales, touches de tissu rouge et bronze. Sol central clair et libre, reliefs architecturaux nets, aucune statue ressemblant a un personnage principal.'},
  minero:{anchor:'TOME 1 - CANYONERO',section:'Guide complet des mondes, tome 1, Architecture & Climat ; Le Reveil V2 chapitre 1',status:'adaptation',scene:'Terrasse industrielle de Canyonero, dominant les mines en spirale sous Durane.',prompt:'Les terrasses de Canyonero : large terrasse de roche stratifee et plaques de fer, rails de mine et treuils lourds repartis sur les bords. Perspective ouverte sur le canyon d extraction geant en spirale et la cite de Durane sur le rebord, passerelles metalliques tres lisibles. Cristaux MINERO gris argent dans la roche, soleil oblique et ciel pale, poussiere fine limitee. Deux acces symetriques au plateau, centre libre, aucun effondrement, pas de personnage.'},
  herbo:{anchor:'TOME 10 - VERDANIA',section:'Guide complet des mondes, tome 10, Architecture & Climat ; classeur Ville Arborium',status:'adaptation',scene:'Serre cathedrale d Arborium ; lieu de production original dans l architecture vegetale du guide.',prompt:'La serre d Arborium : tres grande serre cathedrale faite de bois vivant, verre transparent et lianes-ponts, vue a hauteur du sol depuis une allee de pierre couverte de mousse basse. Massifs de plantes et tables de semences sur les bords, canopee habitee en arriere-plan sans personnages visibles. Cristaux HERBO verts dans des niches racinaires, fleurs corail et blanches, rayons de soleil lisibles a travers les vitres. Espace central degage et fertile, aucune racine bloquant la marche.'},
  hemato:{anchor:'TOME 9 - HEMOGLOBIA',section:'Guide complet des mondes, tome 9, Architecture & Climat ; carte V2 Verminia',status:'adaptation',scene:'Cour des grilles de Draevenheim ; decor original prolongeant la scene de Verminia.',prompt:'Les grilles de Draevenheim : cour gothique pavée devant des grilles de fer entrouvertes, manoir de pierre rouge et tours elancees, roses sombres et ronces taillees le long des murs. Fontaine scellee au fond, cristaux HEMATO rose carmin dans les ferrures, clairiere et lunes pales au-dessus des toits. Nuit lisible grace a des lanternes ivoire, pierre grise et feuillage vert froid pour varier la palette. Aucun sang repandu, aucune victime, centre ouvert pour un duel.'},
  necro:{anchor:'TOME 8 - UMBRIA',section:'Guide complet des mondes, tome 8, Architecture & Climat ; classeur Cryptown et Capitaine Skully',status:'adaptation',scene:'Quai souterrain de Cryptown invente ; necropole, obsidienne et lac issus du guide.',prompt:'Le quai de Cryptown : quai de pierre sombre au bord d un lac souterrain tres calme, portes de necropole et piliers d obsidienne en arriere-plan, une embarcation ancienne attachee a droite. Bollards, cordes et petits braseros pales sur les bords, cristaux NECRO violet fume discretement incrustes sous les arches. Reflets argent, murs charbon, bois vert patine, lumiere diffuse rendant chaque marche lisible. Melancolie paisible, aucun squelette personnage, pas de brouillard opaque, centre plat et degage.'},
  geo:{anchor:'Au centre du village, une immense statue',section:'Histoire, chapitre 10, accueil au village de Zarok',status:'adaptation',scene:'Rempart jouable de Zarok, village sculpte dans le canyon ; site canonique, plateforme inventee.',prompt:'Les remparts de Zarok : large place de terre compacte et de pierre gravee devant des maisons taillees dans les parois du canyon, ponts suspendus et toits de metal avec vegetation locale. Monument Rhinoz de pierre noire en arriere-plan : statue d un HUMANOIDE a tete de rhinoceros avec exactement deux bras, deux jambes et une lance. Cristaux GEO ocre dans des bornes, drapeaux verts et blancs, lumiere de fin d apres-midi. Terre humide et canal longeant le bord, sol central bien libre, aucun personnage vivant.'},
  rainbow:{anchor:'TOME 12 - KALISTOPOLIS',section:'Guide complet des mondes, tome 12, description de la cite ; classeur Ville, Temple',status:'invention-symbolique',scene:'Seuil du Temple de Kalistopolis propose V3 ; aucune visite de Kaylis ici n est affirmee pour sa version evasion.',prompt:'Le seuil du Temple de Kalistopolis : vaste parvis de pierre blanche sur une ile suspendue entre mer et ciel, temple monumental au fond, douze petites niches architecturales pour les cristaux autour de la place. Eau, vegetaux, roche et metal coexistent dans des details localises, cristal RAINBOW translucide dans une seule clef de voute. Refractions arc-en-ciel fines sur la pierre, lumiere du matin naturelle, ciel bleu et accents vermillon. Pas de personnage royal, pas de trone, pas de portail noir, aucune explosion de couleurs ; centre simple et degage.'},
  z13:{anchor:'Une taverne au fond du gouffre',section:'Le Reveil V2, chapitre 1, La Gueule Fumante',status:'adaptation-canon',scene:'La Gueule Fumante, taverne ouvriere souterraine de la Z13 au debut du recit.',prompt:'La Gueule Fumante dans la Z13 : salle de taverne ouvriere encastree dans une galerie profonde, plafond bas soutenu de poutres rouillees, comptoir use au fond et tables solides repoussees sur les cotes. Lanternes a bougie sous des cages metalliques, assiettes de pain, chaises marquees par le travail, entree du tunnel visible. Lumiere ambree locale et reflets gris-vert de la mine, air legerement enfume mais architecture nette et entierement lisible. Centre du sol libre, pas de patrons ni de clients, aucun cristal central actif ni aura elementaire.'},
  'trone-fer':{anchor:'La salle haute de la Tour de Fer',section:'Chapitre 16, Le Conseil des Zones, ouverture',status:'adaptation-canon',scene:'Salle haute de la Tour de Fer avec les douze trones massifs et l estrade circulaire du Conseil ; pas un trone de lames emprunte a une autre licence.',prompt:'Le Trone de Fer de Durane, salle du Conseil des Zones : vaste salle circulaire d acier sombre et metal poli, douze sieges massifs disposes autour d une estrade ronde, chaque dossier portant un motif geometrique different sans lettres ni nombres. Grandes baies en hauteur, passerelles techniques et ancien pupitre de retransmission sur le cote. Siege royal en metal forge sobre au fond, PAS un amoncellement depee ni reference a Game of Thrones. Lumiere bleutee naturelle et reflets chauds discrets, sol central degage, aucun dirigeant ni foule, aucun cristal de bonus mis en evidence.'},
  astraball:{anchor:'Je m’appelle Gilmarr.',section:'Chapitre 11, Lanio decouvre le terrain et rencontre Gilmarr',status:'adaptation-canon',scene:'Terrain d Astraball chez les Rhinoz de Zarok ; lieu canonique, details de marquage proposes.',prompt:'Le terrain d Astraball de Zarok : terrain sportif ovale de terre compacte claire dans un canyon habite, limites tracees au sol sans mots, zones de jeu distinctes par des marques simples, buts en anneaux aux extremites. Gradins bas tailles dans la roche, structures de poteaux renforces pour les joueurs Rhinoz, filets lateraux, une balle de cuir posee pres du bord. Grand ciel lumineux et ombres franches, drapeaux vert et blanc, atmosphere joyeuse de sport local sans joueurs ni foule. Terrain entier lisible, aucun cristal donnant un avantage, pas de magie de combat.'},
  ruins:{anchor:null,section:'Creation V3 pour tests neutres, aucune scene canonique revendiquee',status:'invention',scene:'Cour de ruines inventee pour un terrain strictement neutre, hors evenement narratif.',prompt:'Les ruines silencieuses : cour de pierre grise ancienne dans une vallee ordinaire, colonnes brisees basses et arcades ouvertes sur des collines vertes, herbes basses entre les dalles. Quelques fragments de toit rouge patine, lumiere douce de milieu de jour et ciel gris clair. Aucun embleme, aucun cristal, aucun trone, aucune machine, aucun monument de personnage. Sol central plat et entierement libre, acces par les deux cotes, atmosphere neutre et paisible, lieu non rattache a une faction.'}
};
const historyLines = fs.readFileSync(path.join(root,'V3/sources/histoire.txt'),'utf8').split(/\r?\n/);
arenaScenes.astraball.anchor='panier en forme de U invers\u00e9';
arenaScenes.astraball.section='Chapitre 11, L Astraball : Le Jeu des Elements, panier en U inverse et cinq roles';
arenaScenes.astraball.prompt='Le terrain d Astraball de Zarok : terrain sportif improvise mais spacieux en terre compacte pres de la grande place du village, entre des maisons taillees dans le canyon. Le sport utilise pieds et mains, comme un melange de basket et de contact. A chaque extremite, un PANIER EN FORME DE U INVERSE, arche etroite arrondie avec deux montants et filet de reception, de taille humaine proportionnee au terrain ; PAS de cercle de basket, pas anneaux, pas cage de football. Marques au sol simples pour la zone du pilier qui ne peut la quitter et les transitions des cinq roles, sans texte ni chiffres. Gradins bas tailles dans la roche, structures robustes, une balle pres du bord, drapeaux vert et blanc. Grand ciel lumineux, ombres franches, aucun joueur ni foule ni magie. Centre entierement libre. Dimensions exactes, nombre et disposition des paniers sont une extrapolation visuelle, pas une regle additionnelle.';
for(const a of arenas) {
  const info=arenaScenes[a.id];
  const line=info.anchor===null?-1:historyLines.findLastIndex(l=>l.includes(info.anchor));
  if(info.anchor!==null && line<0) throw new Error(`Missing history anchor for ${a.id}`);
  const header=line<0?null:historyLines.slice(0,line+1).findLast(l=>l.startsWith('SOURCE: '));
  a.story_scene=info.scene;
  a.prompt=arenaStyle+' Haute resolution, composition large en perspective HAUTE TROIS-QUARTS, camera au-dessus du sol regardant obliquement vers le bas. Au moins la moitie centrale de la scene est un sol jouable simple destine a recevoir plus tard des cartes superposees, sans dessiner ces cartes. Details concentres en peripherie. Pas de bokeh, pas d orbes decoratives, pas de pastilles lumineuses, pas d arene romaine generique. '+info.prompt;
  a.narrative_status=info.status;
  a.source_history={file:line<0?null:'V3/sources/histoire.txt',docx:header?header.slice(8):null,section:info.section,lineStart:line<0?null:line+1,lineEnd:line<0?null:Math.min(line+8,historyLines.length),anchor:info.anchor};
  a.production={action:a.id==='z13'?'parent-in-progress':a.id==='ruins'?'reuse':'generate',original:a.id==='z13'?null:a.id==='ruins'?'V3/site/assets/arena.webp':`V3/assets/arenas/${a.id}.png`,destination:`V3/site/${a.image}`,doNotModify:a.id==='z13'};
}

const characters = [...new Set(cards.map(c=>c.characterId))].map(characterId=>{
  const versions=cards.filter(c=>c.characterId===characterId);
  return {characterId,name:versions[0].name,aliases:versions[0].aliases,race:versions[0].race,faction:versions[0].faction,cardIds:versions.map(c=>c.id),slugs:versions.map(c=>c.slug),origin:versions[0].source,homeArenas:arenas.filter(a=>a.homeCharacters.includes(characterId)).map(a=>a.id)};
});
const imageAssignments = cards.map(c=>({id:c.id,characterId:c.characterId,slug:c.slug,element:c.element,race:c.race,faction:c.faction,action:c.art_action,source_art:c.source_art,art:c.art,story_scene:c.story_scene,prompt:c.prompt}));
const registry = {version:'V3-repertoire-41',status:'roster-definitif',cardCount:41,characterCount:40,retainedV2Characters:15,retainedV2Cards:16,replacementCards:4,additionalSlots:21,newIdentityCards:25,characters,imageAssignments,assetRequirements:{races:[...new Set(cards.map(c=>c.race))],factions:[...new Set(cards.map(c=>c.faction))],arenas:arenas.map(({id,image,prompt,source_history})=>({id,image,prompt,source_history}))}};

const id = n=>String(30000000+n);
const decks = {player:[1,13,14,5,16,2,21,12,7,18].map(id),enemy:[8,5,11,19,9,17,6,3,4,10].map(id),presets:[
  {id:'z13',name:'Les chemins de la Z13',cards:[21,22,23,25,26,27,34,12,7,31].map(id)},
  {id:'cites',name:'Les cites en eveil',cards:[15,20,24,29,30,21,32,33,28,35].map(id)},
  {id:'frontieres',name:'Les frontieres vivantes',cards:[36,37,38,39,40,41,18,2,6,19].map(id)}
]};

const demo = {
  version:'V3-demo-6-repertoire-41', schema:6, copy_limit:2, rainbow_limit:1, deck_size:10, token_bonus:60, max_turns:200,
  storage:{namespace:'kalistar.v3.',database:'kalistar-v3-cards',instancePattern:'K3-<id>-001',rejectV2Saves:true},
  roster:{cards:41,characters:40,onlyMultipleVersionCharacter:'momo'},
  roles:{1:'Tank',2:'DPS physique',3:'Middle',4:'DPS magique / distance',5:'Support / Healer'},
  roleBounds:max,
  crystalMatchups:{classicAgainstNone:20,rainbowAgainstNone:30,noneAgainstCrystal:0,rainbowAgainstClassic:40,classicAgainstRainbow:-40,classicCycles:'V2 inchanges, voir elements.json',rainbowAgainstRainbow:0,noneAgainstNone:0},
  arena:{elementBonus:15,homeAttack:10,homeDefense:10,maxAttack:25,maxDefense:10,onlyNumeric:true,lockedAfterSetup:true,homeKey:'characterId',noneCountsAsCrystal:false},
  buffPolicy:{revision:'stacked-buffs-20260914',categories:['ward','luck','reraise','mana','physical'],maxChargesPerCategory:1,defenseOrder:['ward','luck','reraise'],automatic:true},
  physical:{face:'buff_atk',phase:'physical',trait:'physical',value:60,targets:'living-ally-including-self',consumeOn:'next-numeric-physical-attack',stacking:'one-per-category'},
  guard:{face:'guard',phase:'guard',trait:'ward',value:60,targets:'living-ally-including-self',requires:'canGuard',allowedRoles:[1,5],consumeOn:'next-numeric-defense-against-physical-attack',persistAcrossDuelRerolls:true,deathBypasses:true,nonConsumingResults:['magic','dodge','death'],stacking:'one-per-category'},
  reraise:{face:'revive',requires:'canHeal',allowedRoles:[5],targets:'living-ally-including-self',consumeOn:'next-elimination-including-death',returnFromGraveyard:false,stacking:'one-per-category'},
  conventions:[
    '41 cartes et 40 personnages. Momo seul possede deux versions. Deux exemplaires par version au maximum et une seule Rainbow par deck. Les presets couvrent l ensemble du repertoire.',
    'Le joueur commence. Les roles alternent apres chaque duel ou action de soutien.',
    'P1 tank ; P2 DPS physique ; P3 middle ; P4 DPS magique ou distance ; P5 support. Une position ne donne pas de bonus statistique automatique. Les deux Momo restent compatibles P3/P4.',
    'NONE signifie sans cristal : sentry=false, magic=[], barriers=[], attaque physique seulement. Aucun halo ni barriere elementaire. Gen et Scrow utilisent des attaques de distance physiques en P4.',
    'Un cristal classique contre NONE ajoute +20 ATK, Rainbow contre NONE +30 ATK, NONE contre cristal 0. Rainbow contre classique +40 et retour classique -40. Les cycles classiques et la matrice armes rouge/vert V2 restent identiques.',
    'Les cinq categories Reraise, trefle, mana, puissance physique et ward sont cumulables, avec une seule charge par categorie. Ordre automatique : ward dans la DEF, puis trefle si le score est insuffisant, puis Reraise si l elimination persiste. Les synergies et bonus de lieu restent cumulables.',
    'Garde est uniquement une face ATK, reservee aux canGuard=true, P1 ou certains P5. Elle remplace l attaque, ouvre la phase guard et attribue ward=60 a un allie vivant du plateau, auteur compris. Aucun bouclier special en DEF dans le repertoire V3.',
    'Ward ajoute +60 DEF a la prochaine defense numerique contre une ATK physique puis est consomme une seule fois. Magie, esquive et Mort ne le consomment pas. Mort contourne ward. Une relance DEF du meme duel conserve le +60 deja applique, sans seconde consommation.',
    'La potion magique remplace l attaque et attribue +60 sur la prochaine attaque numerique magique d un allie vivant, auteur compris. La puissance physique ouvre la phase physical et s attribue aussi a un allie vivant du plateau, auteur compris, pour sa prochaine attaque numerique physique. Le jet numerique du type concerne consomme le trait meme si la cible esquive.',
    'Reraise, face technique revive, est reserve aux soigneurs canHeal=true de role principal P5. Il protege un allie vivant, auteur compris, de sa prochaine elimination meme par Mort ; la carte reste en place. Aucun retour du cimetiere. Il peut etre regagne apres consommation.',
    'Le trefle en ATK est un soutien attribuable a un allie vivant, auteur compris. Si la DEF finale est strictement inferieure a l ATK numerique, il est consomme et relance le de DEF. Egalite, defense suffisante et esquive le conservent. Mort ne le declenche pas.',
    'La face retry en DEF relance immediatement sans jeton. Les jets continuent jusqu a resolution. Les modificateurs et la barriere du nouveau jet sont recalcules ; un ward deja utilise dans ce duel est conserve dans sa formule.',
    'Esquive annule une attaque, y compris Mort. Une barriere ordinaire de -30 ne neutralise pas Mort. Les anciens shields DEF physiques ou magiques ne figurent sur aucune carte V3.',
    'Les arenes donnent +15 ATK au cristal correspondant, +10 ATK/+10 DEF aux characterId locaux. Plafond +25 ATK/+10 DEF, symetrique pour les deux camps, uniquement sur scores numeriques. Aucune affinite elementaire NONE. Le lieu est verrouille apres setup.',
    'Les remplacements compatibles sont effectues avant le duel suivant. Aucun deplacement de carte vivante hors formation initiale. Defaite si plateau vide et aucune reserve compatible ; match nul de demo apres 200 echanges.',
    'V3 utilise schema 6, namespace kalistar.v3., DB kalistar-v3-cards et instances K3-<id>-001. Refuser une partie V2 avec message explicite ; aucun import V2 silencieux et aucune ecriture dans les statistiques V2.',
    'Mode local a deux joueurs ou IA lisant le plateau public sans connaissance des jets futurs. Graine reproductible.'
  ],
  source_specials:'main/Kalistar.xlsx, Capacite Speciale B2:G9 ; CONTRAT_V3.md prioritaire pour Garde et Reraise',
  status:'Profils V3 reequilibres par poste, tests de repertoire automatises ; equilibrage empirique en parties a poursuivre.'
};

write('cartes.json',cards);
write('elements.json',elements);
write('arenes.json',arenas);
write('registre_personnages.json',registry);
write('decks_demo.json',decks);
write('regles_demo.json',demo);
console.log(JSON.stringify({cards:cards.length,characters:characters.length,arenas:arenas.length,images:{copy:imageAssignments.filter(a=>a.action==='copy').length,redraw:imageAssignments.filter(a=>a.action==='redraw').length,generate:imageAssignments.filter(a=>a.action==='generate').length},roles:cards.reduce((a,c)=>(a[c.role]=(a[c.role]||0)+1,a),{})},null,2));
