'use strict';
const L=require('../../atelier/lib.cjs'),R=require('../../atelier/designer-render.cjs'),B=require('../../collaborations/nier-pilot-01/build.cjs'),T=require('../../collaborations/nier-pilot-01/typography.cjs');
const {fs,path,assert,read,write,hash,sharp,ROOT}=L,home=__dirname,REV='2026-10-01-metal-gear-fidelity',file=n=>path.join(home,n),rel=f=>path.relative(ROOT,f).replaceAll('\\','/');
const cards=[['major-ocelot','49600114'],['raiden4','49600102'],['naomi','49592640'],['vamp4','49600105'],['venom-snake','49600115'],['otacon4','49600103'],['the-boss','49600107']].map(([key,id])=>({key,id,kind:'art',rect:[80,156,817,1077],changed:['ILLUSTRATION - cadrage'],art:'V4/Illustrations/MGS_'+key+'_Fidelity_20261001.png'}));
const out=c=>file('work/'+c.key),creation=c=>path.join(ROOT,'V4/creations',c.id);
function evidence(c){const meta=read(path.join(creation(c),'creation.json')),entry=read(path.join(ROOT,'V4/donnees/catalogue.json')).cards.find(e=>e.id===c.id),rev=meta.nativeRevision||entry.nativeRevision;if(rev)return path.dirname(path.join(ROOT,rev.proof));return path.join(ROOT,c.key==='naomi'?'V4/expansions/2026-09-29-fatman-naomi/cards/naomi':'V4/expansions/2026-09-30-metal-gear-saga/cards/'+c.key);}
async function guard(){await L.protectedCheck();await R.verifyAssets();for(const [f,h] of Object.entries(read(file('before.json'))))assert.equal(await hash(path.join(ROOT,f)),h,f);const baseline=read(path.join(ROOT,'V4/releases/2026-10-01-resident-evil/baseline.json'));for(const c of cards){const f=rel(path.join(creation(c),'profile.json'));assert.equal(await hash(path.join(ROOT,f)),baseline.files[f],'Frozen parent profile '+c.id);}}
async function prepare(){
 assert(!fs.existsSync(file('before.json')));await L.protectedCheck();await R.verifyAssets();const observed={},request=[];
 for(const c of cards){const src=creation(c),dest=out(c),old=evidence(c),render=path.join(dest,'render');for(const n of fs.readdirSync(src)){const f=path.join(src,n);if(fs.statSync(f).isFile())observed[rel(f)]=await hash(f);}fs.mkdirSync(render,{recursive:true});fs.cpSync(src,file('originals/'+c.key),{recursive:true});assert.equal(await hash(path.join(old,'card.png')),await hash(path.join(src,'card.png')),'Stale native evidence '+c.key);fs.copyFileSync(path.join(src,'profile.json'),path.join(dest,'profile.json'));const plan=read(path.join(old,'render/composition.json'));for(const l of plan.layers)fs.copyFileSync(path.join(old,'render',l.file),path.join(render,l.file));const art=plan.layers.find(l=>l.name==='ILLUSTRATION - cadrage');assert(art);await sharp(path.join(ROOT,c.art)).resize(737,921,{fit:'cover'}).png().toFile(path.join(render,art.file));fs.copyFileSync(path.join(ROOT,c.art),path.join(dest,'illustration.png'));write(path.join(render,'composition.json'),plan);await sharp(await R.composite(plan.layers.map(l=>({...l,input:path.join(render,l.file)})))).png().toFile(path.join(render,'expected-components.png'));request.push({...c,original:rel(file('originals/'+c.key+'/card.psd')),native:rel(path.join(old,'render/native.json'))});}
 write(file('before.json'),observed);write(file('render-request.json'),{revision:REV,cards:request});await guard();return {prepared:cards.map(c=>c.id)};
}
async function verify(){await guard();const checks=[];for(const c of cards){const dest=out(c),p=read(path.join(dest,'profile.json'));assert(fs.readFileSync(file('originals/'+c.key+'/profile.json')).equals(fs.readFileSync(path.join(dest,'profile.json'))));const v=await B.verifyNative(dest,p),n=read(path.join(dest,'render/native.json'));T.verify(n);const delta=await L.diff(path.join(creation(c),'card.png'),path.join(dest,'card.png'),[c.rect]);assert.equal(delta.outside,0,c.key);assert(delta.changed>0);const audit=read(path.join(dest,'audit.json')),stable=layers=>layers.filter(l=>!c.changed.includes(l.name)).map(({id,...l})=>l);assert.deepEqual(stable(audit.after),stable(audit.before));assert.deepEqual(stable(audit.reopened),stable(audit.before));assert.deepEqual(audit.textsAfter,audit.textsBefore);assert.deepEqual(audit.textsReopened,audit.textsBefore);assert.equal((await L.diff(path.join(dest,'before-without-art.png'),path.join(dest,'after-without-art.png'))).changed,0);write(path.join(dest,'verification.json'),{...v,scope:delta,preservedNativeStyles:true,profileBytesUnchanged:true});await sharp(path.join(dest,'card.png')).resize({width:300}).png().toFile(path.join(dest,'small.png'));checks.push({id:c.id,passed:v.passed,scope:delta,profileHash:await hash(path.join(dest,'profile.json'))});}await guard();write(file('verified.json'),{revision:REV,publication:'awaiting-parent-coordination',cards:checks});return checks;}
async function publicationPlan(){
 await guard();const cat=path.join(ROOT,'V4/donnees/catalogue.json'),catalogueHash=await hash(cat),before=read(cat),catalogue=structuredClone(before),changes=[];
 assert(!fs.existsSync(file('published.json')),'Already published');
 for(const c of cards){const dest=out(c),v=read(path.join(dest,'verification.json')),entry=catalogue.cards.find(e=>e.id===c.id);assert(entry,c.id);assert(v.passed&&v.scope.outside===0&&v.preservedNativeStyles&&v.profileBytesUnchanged);assert.equal(v.profileHash,await hash(path.join(dest,'profile.json')));assert(fs.readFileSync(path.join(dest,'profile.json')).equals(fs.readFileSync(path.join(creation(c),'profile.json'))));assert.deepEqual(entry.profile,read(path.join(dest,'profile.json')));
  for(const n of ['card.png','card.psd'])assert.equal(v.hashes[n],await hash(path.join(dest,n)));
  entry.nativeRevision={id:REV,key:c.key,proof:rel(path.join(dest,'verification.json')),artworkSource:c.art};const meta=read(path.join(creation(c),'creation.json')),names=['card.png','card.psd','verification.json','illustration.png'];for(const n of names)meta.hashes[n]=await hash(path.join(dest,n));meta.nativeRevision=entry.nativeRevision;changes.push({c,meta,names});
 }
 assert.equal(catalogue.cards.length,before.cards.length);for(let i=0;i<before.cards.length;i++){const original=before.cards[i],updated=catalogue.cards[i];if(!cards.some(c=>c.id===original.id))assert.deepEqual(updated,original);else {const {nativeRevision:a,...x}=original,{nativeRevision:b,...y}=updated;assert.deepEqual(y,x);}}
 const G=require('../../atelier/game-catalog.cjs'),oldGame=await G.buildCatalog({published:before.cards.filter(c=>c.kind==='created')}),newGame=await G.buildCatalog({published:catalogue.cards.filter(c=>c.kind==='created')});assert.equal(newGame.cards.length,oldGame.cards.length);
 return {cat,catalogueHash,catalogue,changes,gameCount:newGame.cards.length};
}
async function publish(){
 assert.equal(process.env.KALISTAR_MGS_PARENT_COORDINATED,'2026-10-01','Parent coordination required');const plan=await publicationPlan();await guard();assert.equal(await hash(plan.cat),plan.catalogueHash,'Catalogue changed during preflight');fs.copyFileSync(plan.cat,file('catalogue-before-publication.json'));
 const changed=[];for(const {c,meta,names} of plan.changes){for(const n of names){fs.copyFileSync(path.join(out(c),n),path.join(creation(c),n));changed.push(rel(path.join(creation(c),n)));}write(path.join(creation(c),'creation.json'),meta);changed.push(rel(path.join(creation(c),'creation.json')));}write(plan.cat,plan.catalogue);changed.push(rel(plan.cat));
 for(const c of cards)assert.equal(await hash(path.join(creation(c),'profile.json')),read(file('before.json'))[rel(path.join(creation(c),'profile.json'))]);await L.protectedCheck();write(file('published.json'),{revision:REV,ids:cards.map(c=>c.id),changed,profileBytesUnchanged:true,gameCount:plan.gameCount});return {published:cards.map(c=>c.id),gameCount:plan.gameCount};
}
module.exports={cards,prepare,verify,guard,publicationPlan,publish};
if(require.main===module){const action={prepare,verify,publish,preflight:publicationPlan}[process.argv[2]];assert(action,'Unknown action.');action().then(r=>console.log(JSON.stringify(process.argv[2]==='preflight'?{ready:true,gameCount:r.gameCount,ids:r.changes.map(x=>x.c.id)}:r,null,2))).catch(e=>{console.error(e);process.exitCode=1;});}
