'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const home=__dirname,root=path.resolve(home,'../../..'),SET=path.basename(home);
const rows=[
 ['jill1','jill-valentine-re','JILL VALENTINE','RE1',2,[2],'Gun','AERO','HUMAIN','La porte du manoir','MEMBRE DES S.T.A.R.S.','Jill retient son souffle devant une porte du manoir Spencer. Son experience du terrain ne suffit pas a expliquer ces lieux, mais sa determination lui interdit de laisser ses partenaires sans secours.','adult brunette Jill, blue beret, light blue short sleeve shirt, dark shoulder armor, grey tactical trousers, pistol, Spencer mansion door, tense listening'],
 ['jill3','jill-valentine-re','JILL VALENTINE','RE3',3,[3],'Gun','HYDRO','HUMAIN','Une ville a traverser','SURVIVANTE','Dans une rue de Raccoon City, Jill cherche encore une issue entre les carcasses de voitures. La fatigue marque son visage, sans eteindre sa volonte de survivre et de faire payer Umbrella pour ce desastre.','RE3 remake Jill, short brown bob, blue tank top over white undershirt, dark jeans, holster, pistol, burning Raccoon street, determined exhausted face'],
 ['jill5','jill-valentine-re','JILL VALENTINE','RE5',3,[3],'Gun','CRYO','HUMAIN','Un regard prisonnier','AGENTE SOUS EMPRISE','Le regard de Jill semble lointain sous ses cheveux devenus blonds. Une volonte etrangere dirige ses gestes, mais sous cette discipline glaciale demeure la survivante que Chris refuse de croire perdue.','RE5 controlled Jill, blonde ponytail, fitted purple blue tactical bodysuit, red chest control device, compact pistol, industrial facility, troubled eyes, not sexualized'],
 ['leon2','leon-kennedy-re','LEON S. KENNEDY','RE2',3,[3],'Gun','HYDRO','HUMAIN','Premier jour de cauchemar','POLICIER','Leon avance dans le commissariat avec la prudence maladroite de son premier jour. Il aurait du trouver des collegues et des consignes ; il ne rencontre que le silence, et la responsabilite de proteger les vivants.','RE2 remake young Leon, brown side parted hair, navy RPD police uniform and protective vest, pistol, abandoned police station hallway, worried resolve'],
 ['leon4','leon-kennedy-re','LEON S. KENNEDY','RE4',3,[3],'Gun','PYRO','HUMAIN','Au seuil du village','AGENT SPECIAL','Au seuil du village, Leon comprend que cette mission ne ressemble a aucune autre. Il observe les gestes des habitants et garde son arme prete, avec pour seule priorite de retrouver Ashley et de la ramener vivante.','RE4 remake Leon, brown leather shearling bomber jacket beige fur collar, black tactical shirt gloves, pistol, Spanish rural village, focused wary gaze'],
 ['leon6','leon-kennedy-re','LEON S. KENNEDY','RE6',3,[3],'Gun','NECRO','HUMAIN','Le poids du devoir','AGENT DU DSO','La nuit de Tall Oaks laisse Leon face a une catastrophe qu\'il n\'a pas pu empecher. Au milieu des sirenes et des ombres, il poursuit les responsables, portant chaque survivant rencontre comme une raison de tenir.','RE6 Leon, longer brown fringe, black leather jacket with muted light shoulder panels, dark shirt, pistol, Tall Oaks night, sorrowful determined'],
 ['leon9','leon-kennedy-re','LEON S. KENNEDY','RE9',3,[3],'Poing','MINERO','HUMAIN','Le veter an tient bon'.replace('veter an','veteran'),'AGENT DU DSO','Les annees ont creuse le visage de Leon sans diminuer son instinct. Dans les vestiges d\'une nouvelle enquete, il ferme le poing et reprend appui : la peur lui est familiere, mais abandonner ne l\'est toujours pas.','Resident Evil Requiem older Leon as official 2026 art, weathered face, medium ash brown parted hair, light stubble, dark charcoal jacket over black shirt, black gloves, clenched fist defensive close combat, ruined Midwest corridor; no RE4 shearling jacket'],
 ['ada2','ada-wong-re','ADA WONG','RE2',3,[3],'Gun','NECRO','HUMAIN','Derriere les lunettes','ESPIONNE','Ada traverse le commissariat en gardant ses veritables objectifs pour elle. Derriere ses lunettes, son regard mesure chaque risque ; un geste vers Leon trahit pourtant une attention que sa mission ne reclamait pas.','RE2 remake Ada, black bob, beige trench coat over red dress, dark sunglasses, pistol lowered, police station garage, guarded expression'],
 ['ada4','ada-wong-re','ADA WONG','RE4',2,[2,3],'Dague','HEMATO','HUMAIN','Une autre voie','ESPIONNE','Dans les hauteurs du chateau, Ada choisit sa propre route entre les ordres et les dettes. Sa lame ouvre un passage discret ; elle garde Leon dans son champ de vision sans lui reveler ce qu\'elle est venue chercher.','RE4 remake Ada, short black bob, red ribbed turtleneck long sleeve dress, black tights thigh holster boots, combat knife, castle balcony, calculating concern'],
 ['ada6','ada-wong-re','ADA WONG','RE6',3,[3,4],'Gun','AERO','HUMAIN','La verite dans les flammes','ESPIONNE','Une autre femme a porte son visage et laisse le monde accuser Ada. Dans les coursives, elle remonte la piste de cette usurpation, arme en main, decidee a rendre aux mensonges leur auteur et a reprendre son nom.','RE6 Ada, red collared long sleeve blouse, black fitted leather trousers, shoulder harness gloves, pistol, ship corridor, suspicious alert gaze'],
 ['chris1','chris-redfield-re','CHRIS REDFIELD','RE1',1,[1],'Gun','HERBO','HUMAIN','Tenir le passage','MEMBRE DES S.T.A.R.S.','Chris se place devant ses compagnons dans les couloirs du manoir. Son arme reste ferme malgre l\'incomprehension : il cherche les disparus de Bravo et refuse que les survivants deviennent les prochaines victimes.','RE1 remake Chris, young short brown hair, green tactical vest over light grey short sleeve shirt, dark trousers, pistol, Spencer mansion corridor, protective stance'],
 ['chris5','chris-redfield-re','CHRIS REDFIELD','RE5',1,[1],'Poing','PYRO','HUMAIN','Ne jamais la laisser','AGENT DU BSAA','La chaleur de Kijuju pese sur les epaules de Chris, mais sa recherche de Jill ne faiblit pas. Avec Sheva a ses cotes, il affronte les armes biologiques et les traces d\'un passe qui refuse de rester enterre.','RE5 Chris, very muscular adult short dark hair, green tactical vest, beige short sleeve shirt, cargo trousers gloves, clenched fists, Kijuju sun, fierce protective determination'],
 ['chris6','chris-redfield-re','CHRIS REDFIELD','RE6',1,[1],'Gun','GEO','HUMAIN','Le capitaine revient','CAPITAINE DU BSAA','Chris reprend la tete de son escouade dans une ville dechiree par les combats. Les pertes ne cessent de lui revenir, mais la confiance de ses hommes lui impose de regarder devant lui et de tenir encore la ligne.','RE6 Chris, muscular dark short hair, olive military combat uniform and heavy tactical vest, assault rifle, urban battlefield, exhausted captain protecting squad'],
 ['chris7','chris-redfield-re','CHRIS REDFIELD','RE7',1,[1],'Gun','LUXO','HUMAIN','Sous un nouvel insigne','OPERATEUR','Chris descend dans les installations de Dulvey sous un insigne qu\'il n\'a pas choisi d\'aimer. Il reste attentif aux soldats qui l\'accompagnent : derriere chaque porte, la mission peut encore reclamer une vie.','RE7 Not a Hero Chris, distinct 2017 slimmer face, short brown hair, olive tactical combat gear, plate carrier, rifle, mining tunnel flashlight, no helmet obscuring face, wary resolve'],
 ['chris8','chris-redfield-re','CHRIS REDFIELD','RE8',1,[1],'Gun','CRYO','HUMAIN','Dans la neige du village','CHEF D\'UNITE','Sous son manteau, Chris porte le poids de decisions qu\'il ne peut pas encore expliquer. Dans la neige du village, il avance vers la source du desastre et garde ses hommes unis face a ce qu\'ils vont decouvrir.','RE8 Village Chris, mature heavy muscular build, short dark hair stubble, black long tactical coat over black gear, assault rifle, snow village at night, stern regret'],
 ['claire2','claire-redfield-re','CLAIRE REDFIELD','RE2',2,[2],'Gun','PYRO','HUMAIN','Une promesse a Sherry','SURVIVANTE','Claire etait venue a Raccoon City chercher son frere. Dans les ruines du commissariat, sa priorite change : proteger Sherry, lui ouvrir une issue et lui prouver qu\'au milieu du cauchemar, quelqu\'un restera pres d\'elle.','RE2 remake Claire, auburn ponytail, red leather motorcycle jacket over dark top, jeans, pistol, police station stairway, protective kind determined gaze'],
 ['nemesis3','nemesis-re','NEMESIS','RE3',1,[1],'Poing','NECRO','HUMAIN','La poursuite sans fin','ARME BIOLOGIQUE','Les pas de Nemesis couvrent les sirenes de Raccoon City. Sa silhouette barre la rue comme un ordre d\'Umbrella devenu chair ; aucun obstacle ne detourne longtemps cette arme de la survivante qu\'elle doit eliminer.','RE3 remake Nemesis humanoid first form, massive pale deformed head, exposed teeth, black containment suit straps, huge clenched fists, burning street, no rocket launcher, non graphic'],
 ['mrx2','tyrant-t103-re','MR X','RE2',1,[1],'Poing','MINERO','HUMAIN','Des pas dans le couloir','TYRANT T-103','Un bruit de pas revient derriere les portes du commissariat. Le Tyrant ne se presse pas : sous son manteau, sa force attend le prochain obstacle, tandis que les survivants comprennent que le silence ne les protege plus.','RE2 remake Mr X T103, towering grey bald stern face, black fedora and long black trench coat, black gloves closed fists, police station corridor, implacable humanoid'],
 ['dimitrescu8','alcina-dimitrescu-re','DIMITRESCU','RE8',3,[3,1],'Dague','HEMATO','VAMP','La maitresse du chateau','DAME DU CHATEAU','Dimitrescu accueille l\'intrusion avec une politesse devenue menace. Sous les lustres de son chateau, elle laisse paraitre ses longues griffes, certaine que nul visiteur ne quittera ses salles sans son consentement.','RE8 Lady Alcina Dimitrescu, extremely tall elegant adult woman, ivory long dress black wide brim hat black rose brooch pearl necklace, one gloved hand extending canonical long claws, castle hall, disdainful anger, not sexualized'],
 ['heisenberg8','karl-heisenberg-re','HEISENBERG','RE8',2,[2],'Marteau','ELECTRO','HUMAIN','Le fer lui repond','INGENIEUR','Dans sa fabrique, Heisenberg laisse le metal repondre a son humeur. Son marteau pese contre son epaule ; derriere le rictus et les lunettes, il calcule deja comment retourner la puissance de Miranda contre elle.','RE8 Karl Heisenberg, long greying hair beard, round sunglasses wide brim hat, worn tan long coat, enormous scrap metal hammer over shoulder, factory sparks, defiant grin'],
 ['beneviento8','donna-beneviento-re','BENEVIENTO','RE8',3,[3],'Orbe','NECRO','HUMAIN','Le silence et la poupee','MARIONNETTISTE','Donna demeure immobile sous son voile tandis qu\'Angie semble guetter le visiteur. Dans cette maison coupee du monde, une piece familiere peut devenir un piege, et la peur prete sa voix a ce qui devrait rester inerte.','RE8 Donna Beneviento black mourning dress opaque black veil, holding small canonical cracked white Angie doll in worn bridal gown, quiet domestic workshop, eerie window light; doll clearly separate small object, no extra human limbs'],
 ['moreau8','salvatore-moreau-re','MOREAU','RE8',4,[4],'Lance','HYDRO','HUMAIN','Au bord du reservoir','SEIGNEUR DU LAC','Moreau dissimule son corps sous des tissus detrempes et cherche encore l\'approbation de Miranda. Au bord du reservoir, sa solitude devient une menace : l\'eau trouble cache une violence que sa voix plaintive annonce mal.','RE8 Salvatore Moreau, grotesque hunched humanoid fishlike swollen head and back under ragged dark hooded robe, canonical non graphic form, reservoir wooden walkway, pleading spiteful expression; no invented spear'],
 ['salazar4','ramon-salazar-re','RAMON SALAZAR','RE4',5,[5,4],'Orbe','NECRO','HUMAIN','L\'orgueil du dernier heritier','CHATELAIN','Ramon Salazar contemple son domaine comme un theatre dont il possede chaque issue. Sa petitesse ne tempere pas son orgueil : il offre ses salles et ses serviteurs au culte, certain que Leon finira par s\'y briser.','RE4 remake Ramon Salazar small adult man aged pale face powdered curled grey hair, ornate blue grey rococo coat jabot, castle balustrade, contemptuous theatrical hand gesture, no orb prop'],
 ['eveline7','eveline-re','EVELINE','RE7',5,[5,3],'Orbe','NECRO','HUMAIN','La famille imposee','ARME BIOLOGIQUE','Eveline attend dans la maison des Baker avec une idee terrible de la famille. Sa voix parait fragile, mais son desir de retenir chacun pres d\'elle transforme les pieces et les souvenirs en une prison de moisissure.','RE7 Eveline child apparition, long straight black hair, simple grey short sleeve dress, pale solemn face, Baker house doorway black mold on walls, hands lowered, age appropriate, fully clothed, no weapon no gore'],
 ['saddler4','osmund-saddler-re','OSMUND SADDLER','RE4',4,[4],'B\u00e2ton','NECRO','HUMAIN','La voix du culte','CHEF DES ILLUMINADOS','Saddler leve sa canne dans le sanctuaire et parle comme si le monde lui appartenait deja. Ses fideles l\'ecoutent sans discuter ; derriere la ceremonie, Las Plagas prepare une soumission qui ne demande aucun consentement.','RE4 remake Osmund Saddler, aged bearded man bald crown, dark hooded ceremonial robe ornate gold trim, canonical tall staff with fleshy eye finial, island sanctuary candles, commanding cold gaze, no graphic gore']
];
const bounds=require(path.join(root,'V3/donnees/regles_demo.json')).roleBounds;
const cards=rows.map((r,i)=>{
 const [key,characterId,name,faction,role,positions,weapon,element,race,title,job,description,scene]=r;
 const atk=bounds[role].atk.map((v,j)=>v-(j===5?10:15)),defense=bounds[role].defense.map((v,j)=>v-(j===5?10:15));
 atk[5]=role===1?'guard':role===5?'mana':'retry';
 defense[role===1?5:3]=role===1?'retry':'dodge';
 const c={key,id:String(49700101+i),characterId,name,title,job,description,race,weapon,element,faction,collaboration:faction,role,positions,atk,defense,magic:[4],barriers:[5],art:'RE_'+key.replace(/-/g,'_')+'_01.png',crop:{zoom:1,x:0,y:0}};
 if(role===5){c.magic=[5];c.barriers=[6,4];}
 if(key==='salazar4'){c.atk=[160,130,100,'mana','buff_atk',15];c.defense=[190,155,120,85,45,'retry'];c.magic=[6,5];}
 return c;
});
function write(n,v){const f=path.join(home,n);fs.mkdirSync(path.dirname(f),{recursive:true});assert(!fs.existsSync(f),'Refusing overwrite '+n);fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n');}
write('set.json',{id:SET,officialCollaboration:false,arenas:[],presets:[],cards});
const style='Standalone Kalistar narrative fantasy painting, visibly painted strokes, textured color planes, hierarchical edges and worn cloth leather metal. Match supplied Momo and Valazar style references, NOT their characters or dark palette. Not photorealistic, not 3D, not anime. Vertical 4:5 composition for 737x921 window, central face and gesture protected from side columns, visible motivated light and emotional storytelling. One individual scene, no montage, no card frame, text, logos, barcode, watermark or UI. Human characters have one head two arms two legs; canonical monster proportions allowed. ';
for(const [i,c] of cards.entries())write('art-prompts/'+c.key+'.json',{key:c.key,art:c.art,prompt:style+'Subject and moment: '+rows[i][12]+'. Keep canonical episode outfit; do not substitute outfits from other games. Background evocative and restrained; clear readable silhouette and hands.',references:['V3/assets/illustrations/01_ELECTRO_MOMO.png','V3/assets/illustrations/34_NECRO_VALAZAR.png'],status:'awaiting-generation'});
console.log(JSON.stringify({cards:cards.length,ids:[cards[0].id,cards.at(-1).id]}));
