const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),file=path.join(root,'donnees/cartes.json');
const cards=JSON.parse(fs.readFileSync(file));
const elements=JSON.parse(fs.readFileSync(path.join(root,'donnees/elements.json')));
const weapons=Object.keys(JSON.parse(fs.readFileSync(path.join(root,'donnees/armes.json'))));
function add(n,base,changes){
 const id=String(n).padStart(8,'0');if(cards.some(c=>c.id===id))return;
 const c={...cards.find(c=>c.id===String(base).padStart(8,'0')),...changes,id};
 c.slug=String(n).padStart(2,'0')+'_'+c.element+'_'+c.name+(changes.variant?'_'+changes.variant:'');delete c.variant;
 c.art=path.join(root,'assets/illustrations',c.slug.toLowerCase()+'.png').replace(/\\/g,'/');
 c.previous_art=null;c.reference=null;c.color=elements[c.element].color;c.hue=elements[c.element].hue;
 c.weapon_index=weapons.indexOf(c.weapon);c.visual_revision='V2-extension-20';c.barcode_style='spectrum_dark';
 if(c.weapon_index<0)throw new Error(c.weapon);cards.push(c);
}
add(13,1,{name:'TAULIO',title:'GARDE DU CORP LOYAL',job:'PROTECTEUR',positions:[1],weapon:'Poing',atk:[210,167,121,94,55,'buff_atk'],defense:[297,'shield_physical',195,140,100,50],magic:[],barriers:[2],advantage:40,disadvantage:20,text:'Taulio, est un ancien robot de combat imposant utilisé dans la protection rapprochée de VIP. Il a été jeté à la décharge des robots après avoir développé une forte empathie. Malgré cela, il est toujours puissant, loyal et prêt à tout pour protéger ses amis.',source:'Valeurs, effets, texte et exception elementaire de main/V1_P1_FR_Taulio.jpg. Race Robot et faction Chroma confirmees. Arme Poing par lecture du pictogramme.'});
add(14,1,{variant:'CARILLON',title:'LE BAL DES OBJETS PERDUS',job:'MUSICIEN',positions:[3,4],atk:[218,174,136,'retry',70,'mana'],defense:[185,150,121,91,62,25],magic:[6,5,4,2],barriers:[5,3],text:"Pour une nuit, Momo fait danser les objets dont personne ne voulait. Sa flûte soulève les vieux carillons au-dessus de la décharge. Personne n'applaudit. Cela ne l'empêche plus de jouer.",source:'Nouvelle version proposee V2. Identite de Momo conservee ; scene et profil de jeu crees pour les essais.'});
add(15,2,{variant:'ADRESSE',title:"L'ADRESSE EFFACEE",job:'MESSAGERE',positions:[2,5],atk:[220,185,147,108,72,'mana'],defense:[226,188,151,111,75,34],magic:[3],barriers:[5],text:"Le nom a disparu de la porte, mais Cana reconnaît encore la maison. Elle glisse la dernière lettre sous le bois condamné, puis reste un instant dans le vent. Certaines promesses n'attendent aucune réponse.",source:'Nouvelle version proposee V2 de Cana : scene et profil polyvalent crees pour les essais.'});
add(16,5,{variant:'DEGEL',title:'LE PREMIER DEGEL',job:'VEILLEUSE',positions:[4,5],atk:[244,203,162,120,81,'revive'],defense:[220,184,146,110,72,35],magic:[6,5,4,3,2],barriers:[6,4],text:"Malinia entend le lac craquer avant de voir le soleil. Elle baisse enfin son sceptre. Ce qu'elle a protégé tout l'hiver n'a plus besoin d'elle, et cette liberté lui fait presque aussi peur que le froid.",source:'Nouvelle version proposee V2 de Malinia : scene et profil de soutien crees pour les essais.'});
add(17,6,{variant:'VEILLE',title:'LA PRIERE SANS REPONSE',job:'SOIGNEUSE',positions:[3,5],atk:[213,176,142,107,71,'revive'],defense:[230,191,154,114,77,37],magic:[6,5,4,3,2],barriers:[6,2],text:"Aelis a rallumé chaque veilleuse du sanctuaire. Devant la dernière, elle ne demande plus de miracle. Elle reste simplement là, pour que ceux qui reviendront ne trouvent pas la nuit seule à les attendre.",source:'Nouvelle version proposee V2 d Aelis : scene et profil crees pour les essais.'});
add(18,7,{name:'LOK',title:'LA GREVE DU FER',job:'CONTREMAITRE',positions:[2],weapon:'Marteau',atk:[208,186,165,121,99,77],defense:[296,264,202,148,110,91],magic:[6,4],barriers:[5],text:"Lok bloque le convoi de minerai au milieu de la fonderie. Pour la première fois, le vacarme s'arrête avant la cloche. Sa main tremble sur le levier ; cette fois, il ne remettra pas la machine en marche.",source:'Nom, race, cristal, faction, position et 12 valeurs de main/Kalistar.xlsx, Personnages ligne 14. Arme, metier, effets et scene proposes V2. Profil DEF eleve conserve malgre le role P2.'});
add(19,11,{name:'BELROG',element:'MINERO',title:'LE SILENCE DE LA MONTAGNE',job:'ECLAIREUR',positions:[1,3],weapon:'Masse',atk:[237,198,158,119,79,38],defense:[259,218,174,130,86,42],magic:[6,3],barriers:[5,2],text:"Au sommet du col, Belrog redresse le signal renversé par l'avalanche. La vallée ne répond pas encore. Il attend debout, couvert de poussière, jusqu'à distinguer une première lumière au loin.",source:'Nom Belrog, race Rhinoz, cristal MINERO et faction Zarok de main/Kalistar.xlsx, Personnages ligne 2. Autres champs et scene proposes V2.'});
add(20,9,{variant:'LIENS',title:'LES LIENS ROMPUS',job:'DISSIDENTE',positions:[4],weapon:'Tome',atk:[284,236,189,142,94,44],defense:[187,154,123,92,61,'dodge'],magic:[6,5,4,3,2,1],barriers:[6,4],text:"Verminia défait le sceau de sa maison sans refermer le livre. Le dernier fil rouge résiste, puis cède entre ses doigts. Elle ne cherche plus à effacer son nom : elle commence à décider ce qu'il signifiera.",source:'Nouvelle version proposee V2 de Verminia : scene et profil magique crees pour les essais.'});
if(cards.length!==20||new Set(cards.map(c=>c.id)).size!==20)throw new Error('Expected 20 stable IDs');
fs.writeFileSync(file,JSON.stringify(cards,null,2));
fs.writeFileSync(path.join(root,'donnees/registre_identifiants.json'),JSON.stringify(cards.map(c=>({id:c.id,personnage:c.name,version:c.title,element:c.element,fichier:c.slug})),null,2));
fs.writeFileSync(path.join(root,'donnees/decks_demo.json'),JSON.stringify({player:['00000001','00000013','00000014','00000005','00000016','00000002','00000015','00000012','00000007','00000017'],enemy:['00000008','00000018','00000011','00000019','00000009','00000020','00000006','00000003','00000004','00000010']},null,2));
console.log('20 versions, 15 personnages, 20 IDs. Original 12 game profiles untouched.');
